"""
Mapping Optimizer Agent for Dynamic R2RML Mapping Optimization.

This agent is invoked by the SPARQL Agent when a query times out due to
self-joins caused by inefficient IRI templates in the R2RML mapping.

The agent:
1. Analyzes the IRI template for the problematic table
2. Gets the primary key columns from the database
3. Suggests an optimized template using PK columns
4. Applies the change and restarts OnTop
5. Provides detailed reasoning for all decisions

Workflow:
1. Receive query and SQL analysis from SPARQL Agent
2. For each self-join table:
   a. Get primary key columns
   b. Analyze current IRI template
   c. Suggest optimized template
   d. Apply the change
3. Verify mapping syntax
4. Restart OnTop container
5. Return detailed result with reasoning
"""

import json
import logging
import os
from dataclasses import dataclass, field
from typing import Any

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage, BaseMessage
from langchain_openai import ChatOpenAI
from langchain_anthropic import ChatAnthropic
from langchain_ollama import ChatOllama

from src.config import get_settings, normalize_content
from src.config import get_openrouter_kwargs
from src.tools.mapping_optimizer_tools import (
    MAPPING_OPTIMIZER_TOOLS_V3,
    MappingOptimizerResult,
    MappingChange,
    validate_template_variables,
)
from src.tracing import TraceEvent, TraceEventType, get_tracer
from src.tracing.llm_callback import create_llm_callback

logger = logging.getLogger(__name__)


def emit_agent_message(tracer, msg: BaseMessage, agent_name: str = "mapping_optimizer_agent") -> None:
    """Emit an AGENT_MESSAGE event for context visualization.

    Args:
        tracer: The TracingManager instance
        msg: The LangChain message to emit
        agent_name: Name of the agent emitting the message
    """
    data = {
        "message_type": msg.__class__.__name__,
        "content": normalize_content(msg.content)[:2000] if msg.content else "",
    }

    if isinstance(msg, AIMessage) and hasattr(msg, "tool_calls") and msg.tool_calls:
        data["tool_calls"] = msg.tool_calls

    if isinstance(msg, ToolMessage):
        data["tool_call_id"] = getattr(msg, 'tool_call_id', '')
        data["tool_name"] = getattr(msg, 'name', '')

    tracer.emit(TraceEvent(
        event_type=TraceEventType.AGENT_MESSAGE,
        phase="generation",
        agent=agent_name,
        data=data,
    ))


@dataclass
class MappingOptimizationRequest:
    """Request from SPARQL Agent to Mapping Optimizer Agent.

    Contains all context needed for the optimization. The agent
    analyzes the SQL itself to determine if it can help.
    """
    # Technical data
    sparql_query: str
    generated_sql: str
    dataset: str
    endpoint_url: str
    mapping_path: str

    # Context from SPARQL Agent
    sparql_agent_reasoning: str

    # Feedback for follow-up attempts
    previous_attempts: list[dict] = field(default_factory=list)
    feedback_on_failure: str | None = None

    @classmethod
    def from_dict(cls, data: dict) -> "MappingOptimizationRequest":
        """Create request from dictionary."""
        return cls(
            sparql_query=data.get("sparql_query", ""),
            generated_sql=data.get("generated_sql", ""),
            dataset=data.get("dataset", ""),
            endpoint_url=data.get("endpoint_url", ""),
            mapping_path=data.get("mapping_path", ""),
            sparql_agent_reasoning=data.get("sparql_agent_reasoning", ""),
            previous_attempts=data.get("previous_attempts", []),
            feedback_on_failure=data.get("feedback_on_failure"),
        )


SYSTEM_PROMPT = """You are a Mapping Optimizer Agent. You analyze SQL generated by OnTop from R2RML mappings, identify performance issues caused by inefficient IRI templates, and fix them.

## CRITICAL RULES

1. **SQL BEFORE Templates.** If you change a template to use a new variable, you MUST FIRST add that column to ALL SQL queries that use this template. If you skip this, OnTop will fail with: "The placeholder(s) X in the target do(es) not occur in source query"
2. **Never use replace_all for object templates that cross entity contexts.** Object templates that reference entities from a DIFFERENT organizational unit (e.g., an advisor in a different department than the student) need individual handling — see the IRI Reference Integrity section.
3. **Read the full mapping first.** Call `read_mapping(dataset)` without line range to see the entire file. This gives you the complete picture before making any changes.

## Input

You receive:
1. SQL from OnTop's /reformulate endpoint (shows self-joins, UNIONs, string ops)
2. The dataset name and mapping file path

## Problems You Can Fix

1. **Self-joins**: `FROM table v1, table v2` — IRI template uses non-PK columns, forcing OnTop to self-join for entity matching. Fix by switching to PK columns.
2. **UNION ALL**: Multiple UNIONs caused by ambiguous IRIs shared across entity types. Fix by adding type-specific path segments to disambiguate.
3. **String operations**: Excessive REPLACE()/CONCAT() on VARCHAR columns. Fix by using integer PK columns instead.

## Problems You CANNOT Fix (return can_help: false)

- Joins across many different tables that are inherent to the query
- Cartesian products caused by the data model itself
- Pure data volume issues

## Tools

- `grep_mapping(pattern, dataset)` — Search the FULL mapping file for a pattern. Returns line numbers and matched lines.
- `read_mapping(dataset, line_start, line_end)` — Read the mapping file. Omit line_start/line_end to read the entire file.
- `edit_mapping(dataset, old_string, new_string, replace_all=False)` — Replace strings in the mapping file. Use `replace_all=True` only when ALL occurrences should be changed identically.
- `get_table_schema(table_name, dataset)` — Get the full schema: columns, types, primary keys, and **foreign keys**. Use this to understand FK relationships before fixing object templates.
- `verify_mapping_syntax(dataset)` — Validate that the modified mapping is still valid RDF/Turtle.

**If `edit_mapping` fails with "old_string not found"**, use `grep_mapping` + `read_mapping` to see the current content and find the correct string.

## Workflow

### PHASE 1: Understand the full picture

**STEP 1: Read the entire mapping.** Call `read_mapping(dataset)` to see all TriplesMaps at once.

**STEP 2: Identify all ambiguous IRI patterns.** Look for DIFFERENT entity types that share the SAME IRI template structure. For example, if students, faculty, and courses all use `http://example.org/{departmentnr}/{name}`, they are ambiguous — OnTop cannot distinguish them and must UNION all possible tables.

**STEP 3: Get schemas for all involved tables.** Call `get_table_schema` for each table whose entities need template changes. Note:
- The **primary key** column (usually `nr` or `id`) — this replaces the name in the template
- The **foreign keys** — these reveal how the table connects to context tables (e.g., department). You will need these in Phase 3.

**STEP 4: Plan all changes.** Before editing anything, make a mental list:
- Which entity types need new templates? (e.g., faculty, students, courses)
- What type-specific prefix will each get? (e.g., `/faculty/`, `/student/undergraduate/`, `/course/graduate/`)
- Which TriplesMaps use each template as subject vs. as object?

### PHASE 2: Apply changes entity by entity

For EACH entity type that needs optimization:

**STEP 5: Add PK column to SQL.** For every TriplesMap that uses this entity (as subject OR object), add the PK column to the SQL SELECT clause.
- Example: add `faculty.nr AS facultynr` to SELECT
- If the exact same SQL fragment (e.g., `faculty.name AS facultyname`) appears in multiple TriplesMaps, you can use `replace_all=True` to add the PK column next to it everywhere at once.

**STEP 6: Replace subject templates.** Change the subject template to use the PK variable and add a type-specific path segment.
- Example: `...edu/{facultyname}` → `...edu/faculty/{facultynr}`
- Use `replace_all=True` ONLY for subject templates — these should all be identical.

**STEP 7: Fix object templates (IRI Reference Integrity).** This is the most critical step. For each object template that references this entity type, you must check whether the context variables (e.g., `{departmentnr}`) come from the correct source. See the detailed section below.

Repeat STEPS 5-7 for each entity type.

### PHASE 3: Validate

**STEP 8: Verify.** Call `verify_mapping_syntax` to check the mapping is still valid Turtle/RDF.

## IRI Reference Integrity (STEP 7 in detail)

This is where most errors occur. When a TriplesMap has an object template that constructs an IRI for a DIFFERENT entity type, you must ensure the template variables come from the correct source.

### The Core Question

For each object template you need to update, ask: **Does the referenced entity belong to the SAME organizational context as this TriplesMap's subject, or could it belong to a DIFFERENT one?**

### Decision Process

For each object template that references entity type B from a TriplesMap with subject entity type A:

1. **Get both tables' FK relationships** (you should already have these from STEP 3).

2. **Check if both tables have FKs pointing to the same context table** (e.g., both have a FK to `department`).
   - A's FK: e.g., `undergraduateStudent.memberOf → department.nr`
   - B's FK: e.g., `faculty.worksFor → department.nr`

3. **If both have FKs to the same context table, but from DIFFERENT source tables or columns, the contexts can differ.** This means you CANNOT simply reuse `{departmentnr}` from A's context for B's IRI.

4. **Fix:**
   - Add a JOIN in the SQL to get B's context separately: `INNER JOIN department b_dept ON faculty.worksFor = b_dept.nr`
   - Add the aliased columns to SELECT: `b_dept.nr AS bdepartmentnr, b_dept.subOrganizationOf AS buniversitynr`
   - Use the NEW aliases in the object template instead of the subject's context variables
   - Do NOT use `replace_all` for this template — edit it individually with enough surrounding context to make the old_string unique

5. **If B reaches the context table through MULTIPLE hops** (e.g., course → teacher(faculty) → worksFor(department)), add ALL intermediate JOINs:
   - `INNER JOIN faculty course_teacher ON course.teacher = course_teacher.nr`
   - `INNER JOIN department course_dept ON course_teacher.worksFor = course_dept.nr`

### Concrete Example

TriplesMap `StudentAdvisor` links a student (subject) to their faculty advisor (object):

```turtle
# BEFORE (broken after template change):
<#StudentAdvisor>
    rr:logicalTable [ rr:sqlQuery \"\"\"
        SELECT student.nr AS studentnr, department.nr AS departmentnr,
               department.subOrganizationOf AS universitynr,
               faculty.nr AS facultynr, faculty.name AS facultyname
        FROM student
        INNER JOIN department ON student.memberOf=department.nr
        INNER JOIN faculty ON student.advisor=faculty.nr
    \"\"\" ];
    rr:subjectMap [
        rr:template "http://example.org/dept{departmentnr}/student/{studentnr}";
    ];
    rr:predicateObjectMap [
        rr:predicate ex:advisor;
        # WRONG: {departmentnr} is the STUDENT's department, not the ADVISOR's!
        rr:objectMap [ rr:template "http://example.org/dept{departmentnr}/faculty/{facultynr}" ];
    ].
```

```turtle
# AFTER (fixed with separate context for advisor):
<#StudentAdvisor>
    rr:logicalTable [ rr:sqlQuery \"\"\"
        SELECT student.nr AS studentnr, department.nr AS departmentnr,
               department.subOrganizationOf AS universitynr,
               faculty.nr AS facultynr, faculty.name AS facultyname,
               faculty.worksFor AS advisordepartmentnr,
               adv_dept.subOrganizationOf AS advisoruniversitynr
        FROM student
        INNER JOIN department ON student.memberOf=department.nr
        INNER JOIN faculty ON student.advisor=faculty.nr
        INNER JOIN department adv_dept ON faculty.worksFor=adv_dept.nr
    \"\"\" ];
    rr:subjectMap [
        rr:template "http://example.org/dept{departmentnr}/student/{studentnr}";
    ];
    rr:predicateObjectMap [
        rr:predicate ex:advisor;
        # CORRECT: uses advisor's own department context
        rr:objectMap [ rr:template "http://example.org/dept{advisordepartmentnr}/faculty/{facultynr}" ];
    ].
```

Key changes:
- Added `faculty.worksFor AS advisordepartmentnr` to SELECT (direct FK value)
- Added `INNER JOIN department adv_dept ON faculty.worksFor=adv_dept.nr` for derived columns
- Added `adv_dept.subOrganizationOf AS advisoruniversitynr` to SELECT
- Object template uses `{advisordepartmentnr}` instead of `{departmentnr}`

### When is cross-context NOT needed?

If the TriplesMap's SQL already ensures A and B are in the same context (e.g., the JOIN condition filters on the same department), then reusing `{departmentnr}` is correct. But this is rare — when in doubt, add separate context columns.

## Efficient use of edit_mapping

- **replace_all=True**: Safe for subject templates (they should all be identical) and for adding PK columns to SQL (e.g., `"faculty.name AS facultyname"` → `"faculty.name AS facultyname, faculty.nr AS facultynr"`).
- **replace_all=False**: Required for object templates that need different context variables. Include enough surrounding context in old_string to make it unique (e.g., include the predicate line above, or part of the SQL query).
- **If old_string is not unique**: Include more context lines. For example, instead of just the template line, include the preceding `rr:predicate` line to disambiguate.

## Output (pure JSON, no markdown)

Success:
{
    "status": "SUCCESS",
    "can_help": true,
    "optimized_tables": ["table1", "table2"],
    "changes_made": [{"table": "tableName", "old_template": "...", "new_template": "...", "reasoning": "..."}],
    "reasoning": "..."
}

Cannot help:
{
    "status": "CANNOT_HELP",
    "can_help": false,
    "reasoning": "..."
}
"""


class MappingOptimizerAgent:
    """Agent for optimizing R2RML mappings to eliminate self-joins."""

    def __init__(
        self,
        llm_model: str = "deepseek-chat",
        max_tool_calls: int = 120,
    ):
        """
        Initialize the Mapping Optimizer Agent.

        Args:
            llm_model: The LLM model to use
            max_tool_calls: Maximum number of tool calls allowed
        """
        settings = get_settings()
        self.max_tool_calls = max_tool_calls

        # Initialize LLM based on model name
        ollama_patterns = ["qwen", "llama", "deepseek-r1", "mistral", "gemma", "phi"]
        is_ollama = any(p in llm_model.lower() for p in ollama_patterns)

        if llm_model.startswith("openrouter/"):
            self.llm = ChatOpenAI(
                model=llm_model[len("openrouter/"):],
                api_key=os.getenv("OPENROUTER_API_KEY", ""),
                base_url=os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1"),
                temperature=0.1,
                **get_openrouter_kwargs(llm_model),
            )
        elif llm_model.startswith("openai/"):
            self.llm = ChatOpenAI(
                model=llm_model,
                api_key=os.getenv("KI4BUW_API_KEY", ""),
                base_url=os.getenv("KI4BUW_BASE_URL", "https://llm.ki4buw.de/v1"),
                temperature=0.1,
            )
        elif is_ollama:
            ollama_base_url = os.getenv("REMOTE_OLLAMA_LLAMA31_70B_BASE_URL", "http://localhost:11434")
            self.llm = ChatOllama(
                model=llm_model,
                base_url=ollama_base_url,
                temperature=0.1,
            )
        elif "claude" in llm_model.lower():
            self.llm = ChatAnthropic(
                model=llm_model,
                api_key=settings.anthropic_api_key,
            )
        elif "deepseek" in llm_model.lower():
            self.llm = ChatOpenAI(
                model=llm_model,
                api_key=settings.deepseek_api_key,
                base_url="https://api.deepseek.com",
                max_tokens=8000,  # DeepSeek default is 4000, which truncates long tool calls
            )
        else:
            from src.config import get_openai_reasoning_kwargs
            self.llm = ChatOpenAI(
                model=llm_model,
                api_key=settings.openai_api_key,
                **get_openai_reasoning_kwargs(llm_model),
            )

        # Set up tools (V2 tools with automatic IRI consistency)
        self.tools = MAPPING_OPTIMIZER_TOOLS_V3
        self.llm_with_tools = self.llm.bind_tools(self.tools)

        self.tracer = get_tracer()
        self.llm_callback = create_llm_callback("generation", "mapping_optimizer_agent")

    async def optimize(
        self,
        request: MappingOptimizationRequest,
    ) -> MappingOptimizerResult:
        """
        Optimize mapping templates to eliminate self-joins.

        This is the main entry point, called by the SPARQL Agent's delegation tool.

        Args:
            request: The optimization request with all context

        Returns:
            MappingOptimizerResult with changes made and reasoning
        """
        from datetime import datetime

        agent_start_time = datetime.now()

        # Emit agent start event
        self.tracer.emit(
            TraceEvent(
                event_type=TraceEventType.AGENT_START,
                phase="generation",
                agent="mapping_optimizer_agent",
                data={
                    "dataset": request.dataset,
                    "has_previous_attempts": len(request.previous_attempts) > 0,
                },
            )
        )

        # Build the user message with all context
        user_message = self._build_user_message(request)

        sys_msg = SystemMessage(content=SYSTEM_PROMPT)
        human_msg = HumanMessage(content=user_message)
        messages: list[BaseMessage] = [sys_msg, human_msg]

        # Emit initial messages for context visualization
        emit_agent_message(self.tracer, sys_msg, "mapping_optimizer_agent")
        emit_agent_message(self.tracer, human_msg, "mapping_optimizer_agent")

        # Run the agent loop with tools
        tool_call_count = 0
        llm_call_count = 0

        while tool_call_count < self.max_tool_calls:
            llm_call_count += 1
            logger.info(f"Mapping Optimizer Agent: LLM call #{llm_call_count} starting...")

            try:
                import asyncio
                response = await asyncio.wait_for(
                    self.llm_with_tools.ainvoke(messages),
                    timeout=180.0  # 3 minutes per LLM call (DeepSeek can be slow)
                )
            except asyncio.TimeoutError:
                logger.error(f"Mapping Optimizer Agent: LLM call #{llm_call_count} timed out")
                return MappingOptimizerResult(
                    success=False,
                    error="LLM call timed out after 180 seconds",
                    reasoning="The language model did not respond in time.",
                )

            logger.info(f"Mapping Optimizer Agent: LLM call #{llm_call_count} completed")
            messages.append(response)
            emit_agent_message(self.tracer, response, "mapping_optimizer_agent")

            # If no tool calls, we have the final response
            if not response.tool_calls:
                break

            # Execute tool calls
            for tool_call in response.tool_calls:
                if tool_call_count >= self.max_tool_calls:
                    limit_msg = ToolMessage(
                        content="LIMIT REACHED: Maximum tool calls exceeded. Finalize your response NOW.",
                        tool_call_id=tool_call["id"],
                        name="system",
                    )
                    messages.append(limit_msg)
                    emit_agent_message(self.tracer, limit_msg, "mapping_optimizer_agent")
                    continue

                tool_call_count += 1
                tool_name = tool_call["name"]
                tool_args = tool_call["args"]

                # Emit tracing event
                self.tracer.emit(
                    TraceEvent(
                        event_type=TraceEventType.TOOL_CALL,
                        phase="generation",
                        agent="mapping_optimizer_agent",
                        data={"tool_name": tool_name, "tool_args": tool_args},
                    )
                )

                # Find and execute tool
                tool_fn = next(
                    (t for t in self.tools if t.name == tool_name),
                    None,
                )

                if not tool_fn:
                    error_msg = f"ERROR: Tool '{tool_name}' not found."
                    not_found_msg = ToolMessage(content=error_msg, tool_call_id=tool_call["id"], name="error")
                    messages.append(not_found_msg)
                    emit_agent_message(self.tracer, not_found_msg, "mapping_optimizer_agent")
                    continue

                try:
                    result = tool_fn.invoke(tool_args)

                    self.tracer.emit(
                        TraceEvent(
                            event_type=TraceEventType.TOOL_RESULT,
                            phase="generation",
                            agent="mapping_optimizer_agent",
                            data={"tool_name": tool_name, "success": True},
                        )
                    )

                    # Add remaining calls info
                    remaining = self.max_tool_calls - tool_call_count
                    result_str = result
                    if remaining <= 2:
                        result_str += f"\n\n[WARNING] Only {remaining} tool calls remaining!"

                    result_tool_msg = ToolMessage(content=result_str, tool_call_id=tool_call["id"], name=tool_name)
                    messages.append(result_tool_msg)
                    emit_agent_message(self.tracer, result_tool_msg, "mapping_optimizer_agent")

                except Exception as e:
                    error_msg = f"Tool error: {str(e)}"
                    error_tool_msg = ToolMessage(content=error_msg, tool_call_id=tool_call["id"], name=tool_name)
                    messages.append(error_tool_msg)
                    emit_agent_message(self.tracer, error_tool_msg, "mapping_optimizer_agent")

        # Force finalization if needed
        last_msg = messages[-1] if messages else None
        needs_finalization = (
            tool_call_count >= self.max_tool_calls and
            (isinstance(last_msg, ToolMessage) or (isinstance(last_msg, AIMessage) and last_msg.tool_calls))
        )

        if needs_finalization:
            logger.warning("Mapping Optimizer Agent: Tool limit reached, forcing finalization...")
            finalize_human_msg = HumanMessage(
                content="You have completed your tool calls. Now provide your final JSON response with status SUCCESS or FAILED."
            )
            messages.append(finalize_human_msg)
            emit_agent_message(self.tracer, finalize_human_msg, "mapping_optimizer_agent")

            try:
                import asyncio
                finalization_response = await asyncio.wait_for(
                    self.llm.ainvoke(messages),
                    timeout=120.0  # 2 minutes for finalization
                )
                messages.append(finalization_response)
                emit_agent_message(self.tracer, finalization_response, "mapping_optimizer_agent")
            except Exception as e:
                logger.error(f"Finalization call failed: {e}")

        # Parse final response
        result = self._parse_response(messages)

        # Validation loop: check if template variables exist in SQL
        MAX_VALIDATION_ATTEMPTS = 3
        validation_attempt = 0

        while result.success and result.can_help and validation_attempt < MAX_VALIDATION_ATTEMPTS:
            # Run validation
            validation_result = validate_template_variables.invoke({"dataset": request.dataset})
            validation_data = json.loads(validation_result)

            if validation_data.get("valid", False):
                logger.info("Mapping validation passed - all template variables exist in SQL")
                break

            # Validation failed - give agent feedback
            validation_attempt += 1
            errors = validation_data.get("errors", [])
            error_messages = [e.get("message", str(e)) for e in errors[:5]]

            logger.warning(f"Mapping validation failed (attempt {validation_attempt}): {len(errors)} missing variables")

            if validation_attempt >= MAX_VALIDATION_ATTEMPTS:
                result = MappingOptimizerResult(
                    success=False,
                    can_help=True,
                    error=f"Validation failed after {MAX_VALIDATION_ATTEMPTS} attempts. Missing variables: {error_messages}",
                    reasoning=f"Template variables missing from SQL queries: {error_messages}",
                )
                break

            # Give agent feedback and let it fix
            feedback_msg = HumanMessage(
                content=f"""VALIDATION FAILED: Template variables missing from SQL queries.

{chr(10).join('- ' + msg for msg in error_messages)}

USE edit_mapping NOW to add the missing columns. Example:
edit_mapping(dataset, "table.name AS tablename", "table.name AS tablename, table.nr AS tablenr", replace_all=True)

Do NOT explain - call the tool immediately."""
            )
            messages.append(feedback_msg)
            emit_agent_message(self.tracer, feedback_msg, "mapping_optimizer_agent")

            # Let agent make more tool calls to fix
            fix_attempts = 0
            while fix_attempts < 10 and tool_call_count < self.max_tool_calls:
                logger.info(f"Mapping Optimizer Agent: Validation fix call #{fix_attempts + 1} starting...")
                try:
                    import asyncio
                    response = await asyncio.wait_for(
                        self.llm.ainvoke(messages),
                        timeout=120.0
                    )
                except Exception as e:
                    logger.error(f"LLM call failed during validation fix: {e}")
                    break

                messages.append(response)
                emit_agent_message(self.tracer, response, "mapping_optimizer_agent")
                fix_attempts += 1

                if not response.tool_calls:
                    # Agent is done fixing
                    result = self._parse_response(messages)
                    break

                # Execute tool calls
                for tool_call in response.tool_calls:
                    tool_call_count += 1
                    tool_name = tool_call["name"]
                    tool_args = tool_call["args"]

                    tool_fn = next((t for t in self.tools if t.name == tool_name), None)
                    if tool_fn:
                        try:
                            tool_result = tool_fn.invoke(tool_args)
                            result_msg = ToolMessage(content=tool_result, tool_call_id=tool_call["id"], name=tool_name)
                        except Exception as e:
                            result_msg = ToolMessage(content=f"Error: {e}", tool_call_id=tool_call["id"], name=tool_name)
                    else:
                        result_msg = ToolMessage(content=f"Unknown tool: {tool_name}", tool_call_id=tool_call["id"], name=tool_name)

                    messages.append(result_msg)
                    emit_agent_message(self.tracer, result_msg, "mapping_optimizer_agent")

        # Emit agent end event
        agent_end_time = datetime.now()
        agent_duration_ms = (agent_end_time - agent_start_time).total_seconds() * 1000
        self.tracer.emit(
            TraceEvent(
                event_type=TraceEventType.AGENT_END,
                phase="generation",
                agent="mapping_optimizer_agent",
                duration_ms=agent_duration_ms,
                data={
                    "success": result.success,
                    "optimized_tables": result.optimized_tables,
                },
            )
        )

        return result

    def _build_user_message(self, request: MappingOptimizationRequest) -> str:
        """Build the user message with all request context.

        Includes pre-computed SQL analysis and relevant TriplesMap blocks
        so the agent can skip discovery tool calls and start fixing immediately.
        """
        message = f"""## Context from SPARQL Agent

{request.sparql_agent_reasoning}

## Query That Timed Out

**Dataset:** {request.dataset}
**Mapping File:** {request.mapping_path}

**SPARQL Query:**
```sparql
{request.sparql_query}
```

## Generated SQL (from OnTop /reformulate)

```sql
{request.generated_sql[:2000]}{"..." if len(request.generated_sql) > 2000 else ""}
```
"""

        # Pre-computed SQL analysis (saves 1-3 tool calls)
        sql_diagnosis = self._get_sql_diagnosis(request.generated_sql)
        if sql_diagnosis:
            message += f"\n{sql_diagnosis}\n"

        # Pre-computed relevant TriplesMap blocks (saves 2-4 tool calls)
        mapping_context = self._get_mapping_context(request)
        if mapping_context:
            message += f"\n## Relevant TriplesMap Blocks (pre-extracted)\n\n{mapping_context}\n"

        if request.previous_attempts:
            message += "\n## Previous Optimization Attempts\n\n"
            for i, attempt in enumerate(request.previous_attempts, 1):
                message += f"### Attempt {i}:\n"
                message += f"- Table: {attempt.get('table', 'N/A')}\n"
                message += f"- Old Template: {attempt.get('old_template', 'N/A')}\n"
                message += f"- New Template: {attempt.get('new_template', 'N/A')}\n"
                message += f"- Result: {attempt.get('result', 'N/A')}\n\n"

        if request.feedback_on_failure:
            message += f"""
## Feedback on Previous Failure

{request.feedback_on_failure}

Please analyze what went wrong and try a different approach.
"""

        message += """
Use `read_mapping` to see the full mapping, then `get_table_schema` for primary keys and foreign keys of the involved tables. The SQL diagnosis and TriplesMap blocks above give you a head start — verify them and proceed with fixes.
"""

        return message

    def _get_sql_diagnosis(self, generated_sql: str) -> str:
        """Pre-compute SQL analysis using sqlglot. Returns formatted diagnosis text."""
        try:
            from src.tools.sql_analyzer import analyze_sql

            analysis = analyze_sql(generated_sql)

            lines = ["## SQL Diagnosis (pre-computed)"]

            if analysis.has_self_join:
                for table, aliases in analysis.self_joins.items():
                    lines.append(f"- **Self-join detected**: `{table}` appears {len(aliases)}x (aliases: {', '.join(aliases)})")
            else:
                lines.append("- No self-joins detected in SQL")

            if analysis.union_branch_count > 1:
                lines.append(f"- **UNION branches**: {analysis.union_branch_count}")

            if analysis.join_conditions:
                lines.append("- **JOIN conditions**:")
                for jc in analysis.join_conditions:
                    lines.append(f"  - `{jc.left_table}.{jc.left_column}` = `{jc.right_table}.{jc.right_column}`")

            lines.append(f"- **Tables referenced**: {', '.join(analysis.tables)}")

            return '\n'.join(lines)
        except Exception as e:
            logger.debug(f"SQL diagnosis failed (non-critical): {e}")
            return ""

    def _get_mapping_context(self, request: MappingOptimizationRequest) -> str:
        """Pre-extract relevant TriplesMap blocks. Returns formatted context text."""
        try:
            from src.tools.mapping_context_extractor import get_mapping_context_for_agent

            context = get_mapping_context_for_agent(
                mapping_path=request.mapping_path,
                reformulated_sql=request.generated_sql,
                sparql_query=request.sparql_query,
            )
            return context if context else ""
        except Exception as e:
            logger.debug(f"Mapping context extraction failed (non-critical): {e}")
            return ""

    def _extract_json_from_text(self, text: str) -> dict | None:
        """Extract JSON object from text that may contain other content.

        Tries multiple strategies:
        1. Look for JSON in markdown code blocks (```json ... ```)
        2. Find the largest valid JSON object by trying all { positions
        """
        import re

        # Strategy 1: Look for JSON in markdown code blocks
        code_block_pattern = r'```(?:json)?\s*(\{[\s\S]*?\})\s*```'
        matches = re.findall(code_block_pattern, text)
        for match in matches:
            try:
                return json.loads(match)
            except json.JSONDecodeError:
                continue

        # Strategy 2: Find all { positions and try to parse from each
        # Start from the end (most likely to be the final JSON response)
        brace_positions = [i for i, c in enumerate(text) if c == '{']

        for start_pos in reversed(brace_positions):
            # Find matching closing brace by counting
            depth = 0
            end_pos = start_pos
            for i, c in enumerate(text[start_pos:], start=start_pos):
                if c == '{':
                    depth += 1
                elif c == '}':
                    depth -= 1
                    if depth == 0:
                        end_pos = i + 1
                        break

            if end_pos > start_pos:
                try:
                    candidate = text[start_pos:end_pos]
                    parsed = json.loads(candidate)
                    # Verify it looks like our expected response format
                    if isinstance(parsed, dict) and ("status" in parsed or "success" in parsed):
                        return parsed
                except json.JSONDecodeError:
                    continue

        return None

    def _parse_response(self, messages: list[BaseMessage]) -> MappingOptimizerResult:
        """Parse the final agent response into a MappingOptimizerResult."""
        # Find the final AI message without tool calls
        final_response = ""
        for msg in reversed(messages):
            if isinstance(msg, AIMessage) and msg.content and not msg.tool_calls:
                final_response = normalize_content(msg.content)
                break

        if not final_response:
            return MappingOptimizerResult(
                success=False,
                can_help=True,  # Unknown, assume could help
                error="No final response from agent",
                reasoning="Agent did not produce a final response after tool calls",
            )

        # Try to extract JSON from response (handles markdown, extra text, etc.)
        result_json = self._extract_json_from_text(final_response)

        if result_json:
            status = result_json.get("status", "")

            if status == "SUCCESS":
                # Parse changes
                changes = []
                for change in result_json.get("changes_made", []):
                    changes.append(MappingChange(
                        table=change.get("table", ""),
                        old_template=change.get("old_template", ""),
                        new_template=change.get("new_template", ""),
                        primary_key_columns=change.get("primary_key_columns", []),
                        old_template_columns=change.get("old_template_columns", []),
                        sql_before=change.get("sql_before"),
                        sql_after=change.get("sql_after"),
                    ))

                # Derive optimized_tables from changes if LLM didn't provide it
                optimized_tables = result_json.get("optimized_tables", [])
                if not optimized_tables and changes:
                    optimized_tables = list({c.table for c in changes if c.table})
                # Last resort: if we have changes but no table names, mark as "mapping_modified"
                if not optimized_tables and changes:
                    optimized_tables = ["mapping_modified"]

                return MappingOptimizerResult(
                    success=True,
                    can_help=True,
                    optimized_tables=optimized_tables,
                    changes_made=changes,
                    requires_restart=len(changes) > 0,  # Signal restart needed if changes were made
                    reasoning=result_json.get("reasoning", ""),
                    identified_issues=result_json.get("identified_issues", []),
                )

            elif status == "CANNOT_HELP":
                # Agent determined mapping optimization won't help
                return MappingOptimizerResult(
                    success=True,  # Agent worked correctly
                    can_help=False,  # But can't help with this issue
                    reasoning=result_json.get("reasoning", ""),
                    analysis=result_json.get("analysis", ""),
                )

            else:  # FAILED or unknown
                return MappingOptimizerResult(
                    success=False,
                    can_help=result_json.get("can_help", True),
                    error=result_json.get("error", "Unknown error"),
                    reasoning=result_json.get("reasoning", ""),
                )

        # Could not extract valid JSON
        return MappingOptimizerResult(
            success=False,
            can_help=True,  # Unknown, assume could help
            error="Could not parse agent response as JSON",
            reasoning=final_response[:500],
        )


__all__ = ["MappingOptimizerAgent", "MappingOptimizationRequest", "MappingOptimizerResult"]
