#!/usr/bin/env python3
"""
Convert EDU OWL files to SQL for the edu_large database.

This script parses the OWL/RDF files generated by UBA and converts them
to SQL INSERT statements matching the existing EDU schema.

Usage:
    python scripts/convert_edu_owl_to_sql.py [owl_directory] [output_sql]
"""

import re
import sys
from collections import defaultdict
from pathlib import Path
from xml.etree import ElementTree as ET

# Namespaces
NS = {
    'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
    'ub': 'http://example.org/ontology/education#',
}

# Global ID counters and mappings
uri_to_id = {}
next_id = defaultdict(int)

# Data storage
universities = {}
departments = {}
faculty = {}
professors = {}
lecturers = set()
graduate_students = {}
undergraduate_students = {}
undergraduate_courses = {}
graduate_courses = {}
publications = {}
research_groups = {}
co_authors = []
undergrad_takes_course = []
grad_takes_course = []


def get_id(uri: str, entity_type: str) -> int:
    """Get or create a numeric ID for a URI."""
    if uri not in uri_to_id:
        uri_to_id[uri] = next_id[entity_type]
        next_id[entity_type] += 1
    return uri_to_id[uri]


def extract_uri(element, attr='rdf:about') -> str | None:
    """Extract URI from an element."""
    return element.get(f'{{{NS["rdf"]}}}about') or element.get(f'{{{NS["rdf"]}}}resource')


def extract_ref_uri(element) -> str | None:
    """Extract referenced URI from a child element."""
    resource = element.get(f'{{{NS["rdf"]}}}resource')
    if resource:
        return resource
    # Check for nested element
    for child in element:
        uri = extract_uri(child)
        if uri:
            return uri
    return None


def get_text(parent, tag: str) -> str | None:
    """Get text content of a child element."""
    elem = parent.find(f'eduo:{tag}', NS)
    if elem is not None:
        return elem.text
    return None


def get_ref(parent, tag: str) -> str | None:
    """Get referenced URI from a child element."""
    elem = parent.find(f'eduo:{tag}', NS)
    if elem is not None:
        return extract_ref_uri(elem)
    return None


def get_all_refs(parent, tag: str) -> list[str]:
    """Get all referenced URIs from child elements with the same tag."""
    refs = []
    for elem in parent.findall(f'eduo:{tag}', NS):
        ref = extract_ref_uri(elem)
        if ref:
            refs.append(ref)
    return refs


def parse_owl_file(filepath: Path):
    """Parse a single OWL file and extract entities."""
    try:
        tree = ET.parse(filepath)
        root = tree.getroot()
    except ET.ParseError as e:
        print(f"  Warning: Could not parse {filepath}: {e}")
        return

    for elem in root:
        tag = elem.tag.replace(f'{{{NS["ub"]}}}', '')
        uri = extract_uri(elem)

        if not uri:
            continue

        if tag == 'University':
            uni_id = get_id(uri, 'university')
            universities[uni_id] = {
                'uri': uri,
                'name': get_text(elem, 'name') or f'University{uni_id}',
            }

        elif tag == 'Department':
            dept_id = get_id(uri, 'department')
            sub_org = get_ref(elem, 'subOrganizationOf')
            departments[dept_id] = {
                'uri': uri,
                'name': get_text(elem, 'name') or f'Department{dept_id}',
                'subOrganizationOf': get_id(sub_org, 'university') if sub_org else None,
            }

        elif tag in ('SeniorScholar', 'MidCareerScholar', 'JuniorScholar'):
            fac_id = get_id(uri, 'faculty')
            works_for = get_ref(elem, 'worksFor')
            faculty[fac_id] = {
                'uri': uri,
                'name': get_text(elem, 'name'),
                'telephone': get_text(elem, 'telephone'),
                'emailAddress': get_text(elem, 'emailAddress'),
                'undergraduateDegreeFrom': get_ref(elem, 'undergraduateDegreeFrom'),
                'masterDegreeFrom': get_ref(elem, 'mastersDegreeFrom'),
                'doctoralDegreeFrom': get_ref(elem, 'doctoralDegreeFrom'),
                'worksFor': get_id(works_for, 'department') if works_for else None,
            }
            professors[fac_id] = {
                'professorType': tag,
                'researchInterest': get_text(elem, 'researchInterest'),
                'headOf': None,  # Will be set if found
            }
            # Extract teaching relationships
            for course_uri in get_all_refs(elem, 'teacherOf'):
                if 'GraduateCourse' in course_uri:
                    course_id = get_id(course_uri, 'graduateCourse')
                    if course_id not in graduate_courses:
                        graduate_courses[course_id] = {'uri': course_uri, 'name': None, 'teacher': fac_id}
                    else:
                        graduate_courses[course_id]['teacher'] = fac_id
                else:
                    course_id = get_id(course_uri, 'undergraduateCourse')
                    if course_id not in undergraduate_courses:
                        undergraduate_courses[course_id] = {'uri': course_uri, 'name': None, 'teacher': fac_id, 'teachingAssistant': None}
                    else:
                        undergraduate_courses[course_id]['teacher'] = fac_id

        elif tag == 'Lecturer':
            fac_id = get_id(uri, 'faculty')
            works_for = get_ref(elem, 'worksFor')
            faculty[fac_id] = {
                'uri': uri,
                'name': get_text(elem, 'name'),
                'telephone': get_text(elem, 'telephone'),
                'emailAddress': get_text(elem, 'emailAddress'),
                'undergraduateDegreeFrom': get_ref(elem, 'undergraduateDegreeFrom'),
                'masterDegreeFrom': get_ref(elem, 'mastersDegreeFrom'),
                'doctoralDegreeFrom': get_ref(elem, 'doctoralDegreeFrom'),
                'worksFor': get_id(works_for, 'department') if works_for else None,
            }
            lecturers.add(fac_id)
            # Extract teaching relationships
            for course_uri in get_all_refs(elem, 'teacherOf'):
                course_id = get_id(course_uri, 'undergraduateCourse')
                if course_id not in undergraduate_courses:
                    undergraduate_courses[course_id] = {'uri': course_uri, 'name': None, 'teacher': fac_id, 'teachingAssistant': None}
                else:
                    undergraduate_courses[course_id]['teacher'] = fac_id

        elif tag == 'DoctoralCandidate':
            student_id = get_id(uri, 'graduateStudent')
            member_of = get_ref(elem, 'memberOf')
            advisor = get_ref(elem, 'advisor')
            graduate_students[student_id] = {
                'uri': uri,
                'name': get_text(elem, 'name'),
                'telephone': get_text(elem, 'telephone'),
                'emailAddress': get_text(elem, 'emailAddress'),
                'age': None,
                'undergraduateDegreeFrom': get_ref(elem, 'undergraduateDegreeFrom'),
                'advisor': get_id(advisor, 'faculty') if advisor else None,
                'memberOf': get_id(member_of, 'department') if member_of else None,
            }
            # Course relationships
            for course_uri in get_all_refs(elem, 'takesCourse'):
                course_id = get_id(course_uri, 'graduateCourse')
                grad_takes_course.append((student_id, course_id))
            # Teaching assistant
            for course_uri in get_all_refs(elem, 'tutorOf'):
                course_id = get_id(course_uri, 'undergraduateCourse')
                if course_id in undergraduate_courses:
                    undergraduate_courses[course_id]['teachingAssistant'] = student_id

        elif tag == 'BachelorCandidate':
            student_id = get_id(uri, 'undergraduateStudent')
            member_of = get_ref(elem, 'memberOf')
            advisor = get_ref(elem, 'advisor')
            undergraduate_students[student_id] = {
                'uri': uri,
                'name': get_text(elem, 'name'),
                'telephone': get_text(elem, 'telephone'),
                'emailAddress': get_text(elem, 'emailAddress'),
                'age': None,
                'advisor': get_id(advisor, 'faculty') if advisor else None,
                'memberOf': get_id(member_of, 'department') if member_of else None,
            }
            # Course relationships
            for course_uri in get_all_refs(elem, 'takesCourse'):
                course_id = get_id(course_uri, 'undergraduateCourse')
                undergrad_takes_course.append((student_id, course_id))

        elif tag == 'Publication':
            pub_id = get_id(uri, 'publication')
            main_author = get_ref(elem, 'author')
            publications[pub_id] = {
                'uri': uri,
                'name': get_text(elem, 'name'),
                'title': get_text(elem, 'title'),
                'abstract': get_text(elem, 'abstract'),
                'mainAuthor': get_id(main_author, 'faculty') if main_author else None,
            }
            # Co-authors (graduate students)
            for author_uri in get_all_refs(elem, 'author'):
                if 'DoctoralCandidate' in author_uri:
                    co_authors.append((pub_id, get_id(author_uri, 'graduateStudent')))

        elif tag == 'ResearchGroup':
            rg_id = get_id(uri, 'researchGroup')
            sub_org = get_ref(elem, 'subOrganizationOf')
            research_groups[rg_id] = {
                'uri': uri,
                'subOrganizationOf': get_id(sub_org, 'department') if sub_org else None,
            }

        elif tag in ('GraduateCourse', 'Course'):
            is_grad = tag == 'GraduateCourse' or 'GraduateCourse' in uri
            if is_grad:
                course_id = get_id(uri, 'graduateCourse')
                if course_id not in graduate_courses:
                    graduate_courses[course_id] = {'uri': uri, 'name': get_text(elem, 'name'), 'teacher': None}
                else:
                    graduate_courses[course_id]['name'] = get_text(elem, 'name')
            else:
                course_id = get_id(uri, 'undergraduateCourse')
                if course_id not in undergraduate_courses:
                    undergraduate_courses[course_id] = {'uri': uri, 'name': get_text(elem, 'name'), 'teacher': None, 'teachingAssistant': None}
                else:
                    undergraduate_courses[course_id]['name'] = get_text(elem, 'name')


def escape_sql(value) -> str:
    """Escape a value for SQL."""
    if value is None:
        return 'NULL'
    if isinstance(value, int):
        return str(value)
    escaped = str(value).replace("'", "''").replace("\\", "\\\\")
    return f"'{escaped}'"


def generate_sql(output_path: Path, db_name: str = 'edu_large'):
    """Generate SQL file from parsed data."""
    print(f"\nGenerating SQL to {output_path}...")

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(f"""-- =============================================================================
-- EDU Large Dataset ({len(universities)} Universities)
-- Generated by: scripts/convert_edu_owl_to_sql.py
-- =============================================================================

DROP DATABASE IF EXISTS `{db_name}`;
CREATE DATABASE `{db_name}`;
USE `{db_name}`;

SET FOREIGN_KEY_CHECKS = 0;

-- Schema (same as edu_small)
CREATE TABLE university(
  nr int(11) PRIMARY KEY,
  name varchar(25)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE department (
  nr int(11) PRIMARY KEY,
  name varchar(25),
  subOrganizationOf int(11)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE researchGroup (
  nr int(11) PRIMARY KEY,
  subOrganizationOf int(11)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE faculty (
  nr int(11) PRIMARY KEY,
  name varchar(25),
  telephone varchar(100),
  emailAddress varchar(2000),
  undergraduateDegreeFrom int(11),
  masterDegreeFrom int(11),
  doctoralDegreeFrom int(11),
  worksFor int(11)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE professor (
  nr int(11) PRIMARY KEY,
  professorType varchar(100),
  researchInterest varchar(100),
  headOf int(11)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE lecturer (
  nr int(11) PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE graduateStudent (
  nr int(11) PRIMARY KEY,
  name varchar(25),
  telephone varchar(100),
  emailAddress varchar(2000),
  age int(11),
  undergraduateDegreeFrom int(11),
  advisor int(11),
  memberOf int(11)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE undergraduateStudent (
  nr int(11) PRIMARY KEY,
  name varchar(25),
  telephone varchar(100),
  emailAddress varchar(2000),
  age int(11),
  advisor int(11),
  memberOf int(11)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE undergraduateCourse (
  nr int(11) PRIMARY KEY,
  name varchar(25),
  teacher int(11),
  teachingAssistant int(11)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE graduateCourse (
  nr int(11) PRIMARY KEY,
  name varchar(25),
  teacher int(11)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE publication (
  nr int(11) PRIMARY KEY,
  name varchar(25),
  title varchar(100),
  abstract varchar(1000),
  mainAuthor int(11)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE coAuthorOfPublication (
  publicationID int(11),
  graduateStudentID int(11),
  PRIMARY KEY (publicationID, graduateStudentID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE undergraduateStudentTakeCourse (
  undergraduateStudentID int(11),
  undergraduateCourseID int(11),
  PRIMARY KEY (undergraduateStudentID, undergraduateCourseID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE graduateStudentTakeCourse (
  graduateStudentID int(11),
  graduateCourseID int(11),
  PRIMARY KEY (graduateStudentID, graduateCourseID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- =============================================================================
-- DATA
-- =============================================================================

""")

        # Universities
        print(f"  Writing {len(universities)} universities...")
        if universities:
            f.write(f"-- university: {len(universities)} records\n")
            batch = []
            for nr, data in universities.items():
                batch.append(f"({nr}, {escape_sql(data['name'][:25] if data['name'] else None)})")
                if len(batch) >= 1000:
                    f.write(f"INSERT INTO university (nr, name) VALUES\n{','.join(batch)};\n\n")
                    batch = []
            if batch:
                f.write(f"INSERT INTO university (nr, name) VALUES\n{','.join(batch)};\n\n")

        # Departments
        print(f"  Writing {len(departments)} departments...")
        if departments:
            f.write(f"-- department: {len(departments)} records\n")
            batch = []
            for nr, data in departments.items():
                batch.append(f"({nr}, {escape_sql(data['name'][:25] if data['name'] else None)}, {data['subOrganizationOf'] if data['subOrganizationOf'] is not None else 'NULL'})")
                if len(batch) >= 1000:
                    f.write(f"INSERT INTO department (nr, name, subOrganizationOf) VALUES\n{','.join(batch)};\n\n")
                    batch = []
            if batch:
                f.write(f"INSERT INTO department (nr, name, subOrganizationOf) VALUES\n{','.join(batch)};\n\n")

        # Faculty
        print(f"  Writing {len(faculty)} faculty members...")
        if faculty:
            f.write(f"-- faculty: {len(faculty)} records\n")
            batch = []
            for nr, data in faculty.items():
                udf = get_id(data['undergraduateDegreeFrom'], 'university') if data['undergraduateDegreeFrom'] else 'NULL'
                mdf = get_id(data['masterDegreeFrom'], 'university') if data['masterDegreeFrom'] else 'NULL'
                ddf = get_id(data['doctoralDegreeFrom'], 'university') if data['doctoralDegreeFrom'] else 'NULL'
                wf = data['worksFor'] if data['worksFor'] is not None else 'NULL'
                batch.append(f"({nr}, {escape_sql(data['name'][:25] if data['name'] else None)}, {escape_sql(data['telephone'])}, {escape_sql(data['emailAddress'])}, {udf}, {mdf}, {ddf}, {wf})")
                if len(batch) >= 1000:
                    f.write(f"INSERT INTO faculty (nr, name, telephone, emailAddress, undergraduateDegreeFrom, masterDegreeFrom, doctoralDegreeFrom, worksFor) VALUES\n{','.join(batch)};\n\n")
                    batch = []
            if batch:
                f.write(f"INSERT INTO faculty (nr, name, telephone, emailAddress, undergraduateDegreeFrom, masterDegreeFrom, doctoralDegreeFrom, worksFor) VALUES\n{','.join(batch)};\n\n")

        # Professors
        print(f"  Writing {len(professors)} professors...")
        if professors:
            f.write(f"-- professor: {len(professors)} records\n")
            batch = []
            for nr, data in professors.items():
                batch.append(f"({nr}, {escape_sql(data['professorType'])}, {escape_sql(data['researchInterest'])}, {data['headOf'] if data['headOf'] is not None else 'NULL'})")
                if len(batch) >= 1000:
                    f.write(f"INSERT INTO professor (nr, professorType, researchInterest, headOf) VALUES\n{','.join(batch)};\n\n")
                    batch = []
            if batch:
                f.write(f"INSERT INTO professor (nr, professorType, researchInterest, headOf) VALUES\n{','.join(batch)};\n\n")

        # Lecturers
        print(f"  Writing {len(lecturers)} lecturers...")
        if lecturers:
            f.write(f"-- lecturer: {len(lecturers)} records\n")
            batch = [f"({nr})" for nr in lecturers]
            for i in range(0, len(batch), 1000):
                f.write(f"INSERT INTO lecturer (nr) VALUES\n{','.join(batch[i:i+1000])};\n\n")

        # Graduate Students
        print(f"  Writing {len(graduate_students)} graduate students...")
        if graduate_students:
            f.write(f"-- graduateStudent: {len(graduate_students)} records\n")
            batch = []
            for nr, data in graduate_students.items():
                udf = get_id(data['undergraduateDegreeFrom'], 'university') if data['undergraduateDegreeFrom'] else 'NULL'
                adv = data['advisor'] if data['advisor'] is not None else 'NULL'
                mo = data['memberOf'] if data['memberOf'] is not None else 'NULL'
                batch.append(f"({nr}, {escape_sql(data['name'][:25] if data['name'] else None)}, {escape_sql(data['telephone'])}, {escape_sql(data['emailAddress'])}, NULL, {udf}, {adv}, {mo})")
                if len(batch) >= 1000:
                    f.write(f"INSERT INTO graduateStudent (nr, name, telephone, emailAddress, age, undergraduateDegreeFrom, advisor, memberOf) VALUES\n{','.join(batch)};\n\n")
                    batch = []
            if batch:
                f.write(f"INSERT INTO graduateStudent (nr, name, telephone, emailAddress, age, undergraduateDegreeFrom, advisor, memberOf) VALUES\n{','.join(batch)};\n\n")

        # Undergraduate Students
        print(f"  Writing {len(undergraduate_students)} undergraduate students...")
        if undergraduate_students:
            f.write(f"-- undergraduateStudent: {len(undergraduate_students)} records\n")
            batch = []
            for nr, data in undergraduate_students.items():
                adv = data['advisor'] if data['advisor'] is not None else 'NULL'
                mo = data['memberOf'] if data['memberOf'] is not None else 'NULL'
                batch.append(f"({nr}, {escape_sql(data['name'][:25] if data['name'] else None)}, {escape_sql(data['telephone'])}, {escape_sql(data['emailAddress'])}, NULL, {adv}, {mo})")
                if len(batch) >= 1000:
                    f.write(f"INSERT INTO undergraduateStudent (nr, name, telephone, emailAddress, age, advisor, memberOf) VALUES\n{','.join(batch)};\n\n")
                    batch = []
            if batch:
                f.write(f"INSERT INTO undergraduateStudent (nr, name, telephone, emailAddress, age, advisor, memberOf) VALUES\n{','.join(batch)};\n\n")

        # Undergraduate Courses
        print(f"  Writing {len(undergraduate_courses)} undergraduate courses...")
        if undergraduate_courses:
            f.write(f"-- undergraduateCourse: {len(undergraduate_courses)} records\n")
            batch = []
            for nr, data in undergraduate_courses.items():
                t = data['teacher'] if data['teacher'] is not None else 'NULL'
                ta = data['teachingAssistant'] if data['teachingAssistant'] is not None else 'NULL'
                batch.append(f"({nr}, {escape_sql(data['name'][:25] if data['name'] else None)}, {t}, {ta})")
                if len(batch) >= 1000:
                    f.write(f"INSERT INTO undergraduateCourse (nr, name, teacher, teachingAssistant) VALUES\n{','.join(batch)};\n\n")
                    batch = []
            if batch:
                f.write(f"INSERT INTO undergraduateCourse (nr, name, teacher, teachingAssistant) VALUES\n{','.join(batch)};\n\n")

        # Graduate Courses
        print(f"  Writing {len(graduate_courses)} graduate courses...")
        if graduate_courses:
            f.write(f"-- graduateCourse: {len(graduate_courses)} records\n")
            batch = []
            for nr, data in graduate_courses.items():
                t = data['teacher'] if data['teacher'] is not None else 'NULL'
                batch.append(f"({nr}, {escape_sql(data['name'][:25] if data['name'] else None)}, {t})")
                if len(batch) >= 1000:
                    f.write(f"INSERT INTO graduateCourse (nr, name, teacher) VALUES\n{','.join(batch)};\n\n")
                    batch = []
            if batch:
                f.write(f"INSERT INTO graduateCourse (nr, name, teacher) VALUES\n{','.join(batch)};\n\n")

        # Publications
        print(f"  Writing {len(publications)} publications...")
        if publications:
            f.write(f"-- publication: {len(publications)} records\n")
            batch = []
            for nr, data in publications.items():
                ma = data['mainAuthor'] if data['mainAuthor'] is not None else 'NULL'
                batch.append(f"({nr}, {escape_sql(data['name'][:25] if data['name'] else None)}, {escape_sql(data['title'][:100] if data['title'] else None)}, {escape_sql(data['abstract'][:1000] if data['abstract'] else None)}, {ma})")
                if len(batch) >= 1000:
                    f.write(f"INSERT INTO publication (nr, name, title, abstract, mainAuthor) VALUES\n{','.join(batch)};\n\n")
                    batch = []
            if batch:
                f.write(f"INSERT INTO publication (nr, name, title, abstract, mainAuthor) VALUES\n{','.join(batch)};\n\n")

        # Research Groups
        print(f"  Writing {len(research_groups)} research groups...")
        if research_groups:
            f.write(f"-- researchGroup: {len(research_groups)} records\n")
            batch = []
            for nr, data in research_groups.items():
                so = data['subOrganizationOf'] if data['subOrganizationOf'] is not None else 'NULL'
                batch.append(f"({nr}, {so})")
                if len(batch) >= 1000:
                    f.write(f"INSERT INTO researchGroup (nr, subOrganizationOf) VALUES\n{','.join(batch)};\n\n")
                    batch = []
            if batch:
                f.write(f"INSERT INTO researchGroup (nr, subOrganizationOf) VALUES\n{','.join(batch)};\n\n")

        # Co-authors
        print(f"  Writing {len(co_authors)} co-author relationships...")
        if co_authors:
            f.write(f"-- coAuthorOfPublication: {len(co_authors)} records\n")
            # Deduplicate
            unique_co_authors = list(set(co_authors))
            batch = [f"({pub_id}, {student_id})" for pub_id, student_id in unique_co_authors]
            for i in range(0, len(batch), 1000):
                f.write(f"INSERT INTO coAuthorOfPublication (publicationID, graduateStudentID) VALUES\n{','.join(batch[i:i+1000])};\n\n")

        # Undergrad takes course
        print(f"  Writing {len(undergrad_takes_course)} undergrad-course relationships...")
        if undergrad_takes_course:
            f.write(f"-- undergraduateStudentTakeCourse: {len(undergrad_takes_course)} records\n")
            unique_utc = list(set(undergrad_takes_course))
            batch = [f"({s_id}, {c_id})" for s_id, c_id in unique_utc]
            for i in range(0, len(batch), 1000):
                f.write(f"INSERT INTO undergraduateStudentTakeCourse (undergraduateStudentID, undergraduateCourseID) VALUES\n{','.join(batch[i:i+1000])};\n\n")

        # Grad takes course
        print(f"  Writing {len(grad_takes_course)} grad-course relationships...")
        if grad_takes_course:
            f.write(f"-- graduateStudentTakeCourse: {len(grad_takes_course)} records\n")
            unique_gtc = list(set(grad_takes_course))
            batch = [f"({s_id}, {c_id})" for s_id, c_id in unique_gtc]
            for i in range(0, len(batch), 1000):
                f.write(f"INSERT INTO graduateStudentTakeCourse (graduateStudentID, graduateCourseID) VALUES\n{','.join(batch[i:i+1000])};\n\n")

        f.write("\nSET FOREIGN_KEY_CHECKS = 1;\n")

    print(f"\nDone! Output: {output_path}")
    print(f"Size: {output_path.stat().st_size / 1024 / 1024:.1f} MB")


def main():
    if len(sys.argv) < 2:
        owl_dir = Path(__file__).parent.parent / 'tools'
        output_sql = Path(__file__).parent.parent / 'data' / 'sql' / 'experiment' / '04_edu_large.sql'
    else:
        owl_dir = Path(sys.argv[1])
        output_sql = Path(sys.argv[2]) if len(sys.argv) > 2 else Path('edu_large.sql')

    print(f"Converting EDU OWL files from: {owl_dir}")
    print(f"Output SQL: {output_sql}")

    # Find all OWL files
    owl_files = sorted(owl_dir.glob('University*.owl'))
    print(f"Found {len(owl_files)} OWL files")

    if not owl_files:
        print("No OWL files found!")
        sys.exit(1)

    # Parse all files
    for i, owl_file in enumerate(owl_files):
        if i % 100 == 0:
            print(f"  Parsing file {i+1}/{len(owl_files)}: {owl_file.name}")
        parse_owl_file(owl_file)

    print(f"\nParsed entities:")
    print(f"  Universities: {len(universities)}")
    print(f"  Departments: {len(departments)}")
    print(f"  Faculty: {len(faculty)}")
    print(f"  Professors: {len(professors)}")
    print(f"  Lecturers: {len(lecturers)}")
    print(f"  Graduate Students: {len(graduate_students)}")
    print(f"  Undergraduate Students: {len(undergraduate_students)}")
    print(f"  Undergraduate Courses: {len(undergraduate_courses)}")
    print(f"  Graduate Courses: {len(graduate_courses)}")
    print(f"  Publications: {len(publications)}")
    print(f"  Research Groups: {len(research_groups)}")

    # Generate SQL
    generate_sql(output_sql)


if __name__ == '__main__':
    main()
