"""
CSV to SQL conversion script for TRN and WHOW datasets.

This script converts CSV files to SQL INSERT statements for MySQL.
"""

import csv
import os
import re
from pathlib import Path
from typing import Generator


def sanitize_table_name(filename: str) -> str:
    """Convert filename to valid SQL table name."""
    name = Path(filename).stem.upper()
    # Remove invalid characters
    name = re.sub(r'[^A-Z0-9_]', '_', name)
    return name


def infer_sql_type(values: list[str]) -> str:
    """Infer SQL type from a list of sample values."""
    # Remove empty values
    non_empty = [v for v in values if v.strip()]

    if not non_empty:
        return "TEXT"

    # Check if all values are integers
    try:
        for v in non_empty[:100]:  # Sample first 100
            int(v)
        return "INT"
    except ValueError:
        pass

    # Check if all values are floats
    try:
        for v in non_empty[:100]:
            float(v)
        return "DECIMAL(15,6)"
    except ValueError:
        pass

    # Check max length for VARCHAR vs TEXT
    max_len = max(len(v) for v in non_empty[:1000])
    if max_len <= 255:
        return f"VARCHAR({min(max_len * 2, 255)})"
    else:
        return "TEXT"


def escape_sql_value(value: str) -> str:
    """Escape a value for SQL."""
    if not value or value.strip() == "":
        return "NULL"
    # Escape single quotes
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def csv_to_sql_statements(
    csv_path: Path,
    table_name: str | None = None,
    delimiter: str = ",",
    batch_size: int = 1000
) -> Generator[str, None, None]:
    """
    Convert a CSV file to SQL statements.

    Yields CREATE TABLE and INSERT statements.
    """
    if table_name is None:
        table_name = sanitize_table_name(csv_path.name)

    with open(csv_path, 'r', encoding='utf-8', errors='replace') as f:
        # Try to detect delimiter
        sample = f.read(4096)
        f.seek(0)

        if ';' in sample and ',' not in sample:
            delimiter = ';'

        reader = csv.reader(f, delimiter=delimiter)

        # Get headers
        headers = next(reader)
        headers = [re.sub(r'[^A-Za-z0-9_]', '_', h.strip()) for h in headers]

        # Read all rows to infer types
        rows = list(reader)

    if not rows:
        return

    # Infer column types
    column_types = []
    for i, header in enumerate(headers):
        values = [row[i] if i < len(row) else "" for row in rows[:1000]]
        sql_type = infer_sql_type(values)
        column_types.append(sql_type)

    # Generate CREATE TABLE
    columns_def = ",\n    ".join(
        f"`{h}` {t}" for h, t in zip(headers, column_types)
    )
    yield f"""DROP TABLE IF EXISTS `{table_name}`;
CREATE TABLE `{table_name}` (
    {columns_def}
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""

    # Generate INSERT statements in batches
    for batch_start in range(0, len(rows), batch_size):
        batch = rows[batch_start:batch_start + batch_size]

        values_list = []
        for row in batch:
            # Pad row if necessary
            while len(row) < len(headers):
                row.append("")

            values = ", ".join(escape_sql_value(v) for v in row[:len(headers)])
            values_list.append(f"({values})")

        columns = ", ".join(f"`{h}`" for h in headers)
        yield f"INSERT INTO `{table_name}` ({columns}) VALUES\n" + ",\n".join(values_list) + ";\n"


def convert_trn_to_sql(trn_dir: Path, output_file: Path):
    """Convert all TRN CSV files to a single SQL file."""
    csv_files = list(trn_dir.glob("*.csv"))

    with open(output_file, 'w', encoding='utf-8') as out:
        out.write("-- TRN Dataset SQL Dump\n")
        out.write("-- Generated by csv_to_sql.py\n\n")
        out.write("SET NAMES utf8mb4;\n")
        out.write("SET FOREIGN_KEY_CHECKS = 0;\n\n")

        for csv_file in sorted(csv_files):
            print(f"Converting {csv_file.name}...")
            out.write(f"-- Table: {csv_file.stem}\n")

            for statement in csv_to_sql_statements(csv_file):
                out.write(statement)
                out.write("\n")

        out.write("SET FOREIGN_KEY_CHECKS = 1;\n")

    print(f"Created {output_file}")


def convert_whow_to_sql(whow_dir: Path, output_file: Path):
    """Convert WHOW CSV files to SQL."""
    raw_data_dir = whow_dir / "raw_data"

    if not raw_data_dir.exists():
        print(f"Warning: {raw_data_dir} not found")
        return

    csv_files = list(raw_data_dir.glob("*.csv"))

    with open(output_file, 'w', encoding='utf-8') as out:
        out.write("-- WHOW Dataset SQL Dump\n")
        out.write("-- Generated by csv_to_sql.py\n\n")
        out.write("SET NAMES utf8mb4;\n")
        out.write("SET FOREIGN_KEY_CHECKS = 0;\n\n")

        for csv_file in sorted(csv_files):
            print(f"Converting {csv_file.name}...")
            out.write(f"-- Table: {csv_file.stem}\n")

            try:
                # WHOW uses semicolon delimiter
                for statement in csv_to_sql_statements(csv_file, delimiter=';'):
                    out.write(statement)
                    out.write("\n")
            except Exception as e:
                print(f"  Error: {e}")
                continue

        out.write("SET FOREIGN_KEY_CHECKS = 1;\n")

    print(f"Created {output_file}")


def main():
    """Main entry point."""
    import argparse

    parser = argparse.ArgumentParser(description="Convert CSV to SQL")
    parser.add_argument("--dataset", choices=["trn", "whow", "all"], default="all",
                        help="Which dataset to convert")
    parser.add_argument("--data-dir", type=Path,
                        default=Path(__file__).parent.parent / "data" / "datasets",
                        help="Path to datasets directory")

    args = parser.parse_args()

    if args.dataset in ["trn", "all"]:
        trn_dir = args.data_dir / "TRN"
        if trn_dir.exists():
            output = args.data_dir / "TRN" / "trn_mysql.sql"
            convert_trn_to_sql(trn_dir, output)

    if args.dataset in ["whow", "all"]:
        whow_dir = args.data_dir / "WHOW"
        if whow_dir.exists():
            output = args.data_dir / "WHOW" / "whow_mysql.sql"
            convert_whow_to_sql(whow_dir, output)


if __name__ == "__main__":
    main()
