"""
Mapping Optimizer Tools for dynamically optimizing R2RML mappings.

These tools allow the Mapping Optimizer Agent to:
1. Analyze SQL queries generated by OnTop via /reformulate
2. Detect self-joins that cause performance issues
3. Get primary key information from the database
4. Analyze and modify IRI templates in R2RML mappings
5. Restart OnTop containers to apply changes

The goal is to optimize IRI templates to use primary key columns,
which eliminates unnecessary self-joins in the generated SQL.
"""

import json
import logging
import re
import shutil
import threading
from contextvars import ContextVar
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import httpx
from langchain_core.tools import tool

from src.config import get_settings, MAPPINGS_DIR_ROOT, get_slot_id, SLOT_ENDPOINTS, USE_SLOT_CONTAINERS, get_dataset_size
from src.tools.sparql_tools import get_endpoint_for_dataset
from src.tracing import TraceEvent, TraceEventType, get_tracer

logger = logging.getLogger(__name__)


# =============================================================================
# R2RML Parser using rdflib (Generic - works for all datasets)
# =============================================================================


# R2RML namespace
RR = "http://www.w3.org/ns/r2rml#"


@dataclass
class TripleMapInfo:
    """Information about a single TriplesMap in the R2RML mapping."""
    uri: str  # Full URI of the TriplesMap
    name: str  # Local name (e.g., "BachelorCandidate")
    subject_template: str | None = None
    subject_column: str | None = None  # For rr:column instead of rr:template
    rdf_classes: list[str] = field(default_factory=list)
    logical_table_name: str | None = None  # For rr:tableName
    logical_table_sql: str | None = None   # For rr:sqlQuery
    predicate_object_maps: list[dict] = field(default_factory=list)  # [{predicate, object_template, object_column}, ...]


class R2RMLParser:
    """
    Generic R2RML parser using rdflib.

    Works for ANY R2RML mapping file, regardless of dataset.
    Parses the mapping as an RDF graph and extracts structural information.
    """

    def __init__(self, mapping_path: Path | str):
        """
        Initialize parser with a mapping file.

        Args:
            mapping_path: Path to the R2RML mapping file (.ttl)
        """
        from rdflib import Graph, Namespace, URIRef
        from rdflib.namespace import RDF

        self.path = Path(mapping_path)
        self.graph = Graph()
        self.graph.parse(str(self.path), format="turtle")

        self.RR = Namespace(RR)
        self.RDF = RDF

        self.triples_maps: dict[str, TripleMapInfo] = {}
        self._parse()

    def _parse(self):
        """Parse the R2RML graph to extract all TriplesMaps."""
        from rdflib import Literal, URIRef, BNode

        # Find all subjects that have rr:logicalTable (these are TriplesMaps)
        for tm_uri in self.graph.subjects(self.RR.logicalTable, None):
            # Get local name from URI
            uri_str = str(tm_uri)
            if '#' in uri_str:
                name = uri_str.split('#')[-1]
            else:
                name = uri_str.split('/')[-1]

            info = TripleMapInfo(uri=uri_str, name=name)

            # Get logical table info
            for lt in self.graph.objects(tm_uri, self.RR.logicalTable):
                # Check for tableName
                for tn in self.graph.objects(lt, self.RR.tableName):
                    info.logical_table_name = str(tn)
                # Check for sqlQuery
                for sq in self.graph.objects(lt, self.RR.sqlQuery):
                    info.logical_table_sql = str(sq)

            # Get subject map info
            for sm in self.graph.objects(tm_uri, self.RR.subjectMap):
                # Get template
                for t in self.graph.objects(sm, self.RR.template):
                    info.subject_template = str(t)
                # Get column (alternative to template)
                for c in self.graph.objects(sm, self.RR.column):
                    info.subject_column = str(c)
                # Get rdf:class(es)
                for cls in self.graph.objects(sm, self.RR["class"]):
                    info.rdf_classes.append(str(cls))

            # Get predicate-object maps
            for pom in self.graph.objects(tm_uri, self.RR.predicateObjectMap):
                po_info = {}

                # Get predicate
                for p in self.graph.objects(pom, self.RR.predicate):
                    po_info['predicate'] = str(p)

                # Get object map
                for om in self.graph.objects(pom, self.RR.objectMap):
                    # Check for template
                    for t in self.graph.objects(om, self.RR.template):
                        po_info['object_template'] = str(t)
                    # Check for column
                    for c in self.graph.objects(om, self.RR.column):
                        po_info['object_column'] = str(c)

                if po_info:
                    info.predicate_object_maps.append(po_info)

            self.triples_maps[name] = info

    def extract_template_variables(self, template: str) -> list[str]:
        """
        Extract variable names from an IRI template.

        Args:
            template: IRI template like "http://example.org/{dept}/{name}"

        Returns:
            List of variable names: ["dept", "name"]
        """
        return re.findall(r'\{([^}]+)\}', template)

    def find_templates_with_variable(self, variable: str) -> dict:
        """
        Find all templates that use a specific variable.

        Args:
            variable: Variable name (e.g., "nr", "trip_id", "name")

        Returns:
            Dictionary with 'subject_maps' and 'object_maps' containing
            all TriplesMaps that use this variable in their templates.
        """
        pattern = '{' + variable + '}'
        subject_maps = []
        object_maps = []

        for name, info in self.triples_maps.items():
            # Check subject template
            if info.subject_template and pattern in info.subject_template:
                subject_maps.append({
                    'triples_map': name,
                    'uri': info.uri,
                    'template': info.subject_template,
                    'variables': self.extract_template_variables(info.subject_template),
                    'rdf_classes': info.rdf_classes,
                    'logical_table': info.logical_table_name or info.logical_table_sql,
                })

            # Check object templates
            for po in info.predicate_object_maps:
                if 'object_template' in po and pattern in po['object_template']:
                    object_maps.append({
                        'triples_map': name,
                        'uri': info.uri,
                        'predicate': po.get('predicate'),
                        'template': po['object_template'],
                        'variables': self.extract_template_variables(po['object_template']),
                    })

        return {
            'subject_maps': subject_maps,
            'object_maps': object_maps,
            'total': len(subject_maps) + len(object_maps),
        }

    def find_all_templates(self) -> dict[str, list[dict]]:
        """
        Get all IRI templates in the mapping, grouped by their variable signature.

        This helps identify which templates represent the same entity type
        (they share the same variables).

        Returns:
            Dictionary mapping variable tuple to list of template usages.
            E.g., {("nr",): [{"type": "subject", "triples_map": "...", ...}]}
        """
        templates_by_vars: dict[tuple, list[dict]] = {}

        for name, info in self.triples_maps.items():
            # Subject template
            if info.subject_template:
                vars_tuple = tuple(sorted(self.extract_template_variables(info.subject_template)))
                if vars_tuple not in templates_by_vars:
                    templates_by_vars[vars_tuple] = []
                templates_by_vars[vars_tuple].append({
                    'type': 'subject',
                    'triples_map': name,
                    'template': info.subject_template,
                    'rdf_classes': info.rdf_classes,
                })

            # Object templates
            for po in info.predicate_object_maps:
                if 'object_template' in po:
                    vars_tuple = tuple(sorted(self.extract_template_variables(po['object_template'])))
                    if vars_tuple not in templates_by_vars:
                        templates_by_vars[vars_tuple] = []
                    templates_by_vars[vars_tuple].append({
                        'type': 'object',
                        'triples_map': name,
                        'predicate': po.get('predicate'),
                        'template': po['object_template'],
                    })

        return templates_by_vars

    def get_entity_info(self) -> list[dict]:
        """
        Analyze the mapping to identify distinct entity types and their IRI patterns.

        Returns a list of entities with:
        - variables: The template variables that identify this entity
        - sample_template: One example template
        - subject_count: How many TriplesMaps use this as subject
        - object_count: How many TriplesMaps reference this as object
        - rdf_classes: What RDF classes are associated
        """
        templates_by_vars = self.find_all_templates()

        entities = []
        for vars_tuple, usages in templates_by_vars.items():
            if not vars_tuple:  # Skip empty variable sets
                continue

            subjects = [u for u in usages if u['type'] == 'subject']
            objects = [u for u in usages if u['type'] == 'object']

            # Collect all RDF classes
            all_classes = []
            for s in subjects:
                all_classes.extend(s.get('rdf_classes', []))

            entities.append({
                'variables': list(vars_tuple),
                'sample_template': usages[0]['template'],
                'subject_count': len(subjects),
                'object_count': len(objects),
                'total_usages': len(usages),
                'rdf_classes': list(set(all_classes)),
                'subject_triples_maps': [s['triples_map'] for s in subjects],
                'object_references': [
                    {'triples_map': o['triples_map'], 'predicate': o.get('predicate')}
                    for o in objects
                ],
            })

        # Sort by total usages (most used first)
        entities.sort(key=lambda e: e['total_usages'], reverse=True)

        return entities

    def validate_template_variables(self, old_template: str, new_template: str) -> dict:
        """
        Validate that all variables in the new template are available in affected TriplesMaps.

        This checks that the source queries (SQL) in all TriplesMaps that use this template
        provide the columns needed for the new template variables.

        Args:
            old_template: The current IRI template being replaced
            new_template: The proposed new IRI template

        Returns:
            Dict with:
            - valid: True if all variables are available
            - errors: List of validation errors (if any)
            - affected_triples_maps: List of affected TriplesMaps with their available columns
        """
        old_vars = set(self.extract_template_variables(old_template))
        new_vars = set(self.extract_template_variables(new_template))
        added_vars = new_vars - old_vars  # Variables that are new

        if not added_vars:
            # No new variables, no validation needed
            return {"valid": True, "errors": [], "affected_triples_maps": []}

        errors = []
        affected = []

        # Find all TriplesMaps using this template
        for name, info in self.triples_maps.items():
            uses_template = False

            # Check subject template
            if info.subject_template == old_template:
                uses_template = True

            # Check object templates
            for po in info.predicate_object_maps:
                if po.get('object_template') == old_template:
                    uses_template = True
                    break

            if not uses_template:
                continue

            # Get available columns from the source
            available_cols = self._extract_available_columns(info)

            affected.append({
                "triples_map": name,
                "source_type": "sql_query" if info.logical_table_sql else "table",
                "source": info.logical_table_sql or info.logical_table_name,
                "available_columns": list(available_cols),
            })

            # Check if all new variables are available
            missing = added_vars - available_cols
            if missing:
                errors.append({
                    "triples_map": name,
                    "missing_variables": list(missing),
                    "available_columns": list(available_cols),
                    "source": info.logical_table_sql or info.logical_table_name,
                })

        return {
            "valid": len(errors) == 0,
            "errors": errors,
            "affected_triples_maps": affected,
            "added_variables": list(added_vars),
        }

    def _extract_available_columns(self, info: "TripleMapInfo") -> set[str]:
        """
        Extract available column names from a TriplesMap's logical table.

        For SQL queries, parses the SELECT clause to find column aliases.
        For table names, returns empty set (would need database introspection).
        """
        available = set()

        if info.logical_table_sql:
            # Parse SQL SELECT clause for column names/aliases
            sql = info.logical_table_sql.upper()

            # Find SELECT ... FROM
            select_match = re.search(r'SELECT\s+(.+?)\s+FROM', sql, re.IGNORECASE | re.DOTALL)
            if select_match:
                select_clause = select_match.group(1)

                # Split by comma, handling nested parentheses
                # Simple approach: split by comma and extract aliases
                parts = re.split(r',\s*(?![^()]*\))', select_clause)

                for part in parts:
                    part = part.strip()
                    # Check for AS alias
                    as_match = re.search(r'\s+AS\s+(\w+)\s*$', part, re.IGNORECASE)
                    if as_match:
                        available.add(as_match.group(1).lower())
                    else:
                        # No alias - use column name (last identifier)
                        # Handle table.column
                        col_match = re.search(r'(?:^|\.)(\w+)\s*$', part)
                        if col_match:
                            available.add(col_match.group(1).lower())

        elif info.logical_table_name:
            # For simple table names, we could query the DB for columns
            # But that requires a DB connection. For now, assume all columns available
            # The actual validation will happen when OnTop tries to start
            pass

        return available


# Timeout for reformulate API calls
REFORMULATE_TIMEOUT = 30.0


# =============================================================================
# Data Classes
# =============================================================================


@dataclass
class MappingChange:
    """Details of a single mapping template change."""
    table: str
    old_template: str
    new_template: str
    primary_key_columns: list[str]
    old_template_columns: list[str]
    sql_before: str | None = None
    sql_after: str | None = None


@dataclass
class MappingOptimizerResult:
    """Result from the Mapping Optimizer Agent.

    The `can_help` field indicates whether the agent identified mapping issues
    that it could fix. If False, the SPARQL Agent should try Multi-Step instead.

    The `requires_restart` field indicates whether OnTop needs to be restarted
    to apply mapping changes. The SPARQL Agent handles the restart after receiving
    this result, allowing multiple changes to be batched before a single restart.
    """
    success: bool
    can_help: bool = True  # False if agent determines mapping optimization won't help
    optimized_tables: list[str] = field(default_factory=list)
    changes_made: list[MappingChange] = field(default_factory=list)
    requires_restart: bool = False  # True if mapping was modified and OnTop needs restart
    error: str | None = None
    reasoning: str = ""
    analysis: str = ""  # SQL analysis explanation (especially when can_help=False)
    identified_issues: list[str] = field(default_factory=list)  # What issues were found

    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        return {
            "success": self.success,
            "can_help": self.can_help,
            "optimized_tables": self.optimized_tables,
            "changes_made": [
                {
                    "table": c.table,
                    "old_template": c.old_template,
                    "new_template": c.new_template,
                    "primary_key_columns": c.primary_key_columns,
                    "old_template_columns": c.old_template_columns,
                    "sql_before": c.sql_before,
                    "sql_after": c.sql_after,
                }
                for c in self.changes_made
            ],
            "requires_restart": self.requires_restart,
            "error": self.error,
            "reasoning": self.reasoning,
            "analysis": self.analysis,
            "identified_issues": self.identified_issues,
        }


# =============================================================================
# Context Manager for Mapping Backups
# =============================================================================


class MappingOptimizationContext:
    """Manages temporary mapping changes for a single agent run.

    This context ensures that all mapping changes are reverted when
    the agent run completes (successfully or not).

    When slot_id is set, the context operates on slot-specific mapping files
    and containers, providing isolation for concurrent runs.

    Usage:
        context = MappingOptimizationContext(slot_id=0)  # or None for shared

        # During agent run:
        context.backup_mapping(path, dataset)
        # ... modify mapping ...
        context.mark_modified()

        # At end of agent run:
        context.restore_all()
    """

    def __init__(self, slot_id: int | None = None):
        self.slot_id = slot_id
        self.original_mappings: dict[str, str] = {}  # {path: original_content}
        self.modified: bool = False
        self.affected_datasets: set[str] = set()
        # Initial context parameters for re-reading relevant mapping blocks
        self.initial_mapping_path: str | None = None
        self.initial_reformulated_sql: str | None = None

    def backup_mapping(self, path: str, dataset: str) -> None:
        """Backup a mapping file before modification."""
        if path not in self.original_mappings:
            mapping_path = Path(path)
            if mapping_path.exists():
                self.original_mappings[path] = mapping_path.read_text(encoding="utf-8")
                self.affected_datasets.add(dataset)
                slot_info = f" (slot {self.slot_id})" if self.slot_id is not None else ""
                logger.info(f"Backed up mapping{slot_info}: {path}")

    def mark_modified(self) -> None:
        """Mark that modifications have been made."""
        self.modified = True

    def restore_all(self) -> None:
        """Restore all original mappings and restart affected containers.

        Synchronous implementation to avoid nested event-loop issues.
        When slot_id is set, only restarts the slot-specific containers.
        """
        if not self.original_mappings:
            return

        slot_info = f" (slot {self.slot_id})" if self.slot_id is not None else ""
        logger.info(f"Restoring {len(self.original_mappings)} modified mappings{slot_info}...")

        for path, content in self.original_mappings.items():
            try:
                Path(path).write_text(content, encoding="utf-8")
                logger.info(f"Restored mapping: {path}")
            except Exception as e:
                logger.error(f"Failed to restore mapping {path}: {e}")

        # Restart affected containers (synchronously, slot-aware)
        for dataset in self.affected_datasets:
            try:
                result = restart_ontop_container.invoke({
                    "dataset": dataset,
                    "wait_for_health": True,
                })
                logger.info(f"Container restart for {dataset}{slot_info}: {result}")
            except Exception as e:
                logger.error(f"Failed to restart container for {dataset}: {e}")

        self.original_mappings.clear()
        self.affected_datasets.clear()
        self.modified = False


# Per-task context using ContextVar (thread/async-task local)
# This replaces the global singleton to support concurrent runs with slot isolation
_mapping_context: ContextVar[MappingOptimizationContext | None] = ContextVar(
    "mapping_context", default=None
)


def get_mapping_context() -> MappingOptimizationContext:
    """Get or create the mapping optimization context for the current task.

    The context is task-local (using ContextVar), so each concurrent run
    has its own isolated context with its own slot_id.
    """
    ctx = _mapping_context.get()
    if ctx is None:
        # Create new context with current slot_id from config
        ctx = MappingOptimizationContext(slot_id=get_slot_id())
        _mapping_context.set(ctx)
    return ctx


def reset_mapping_context(slot_id: int | None = None) -> None:
    """Reset the mapping context for a new agent run.

    Args:
        slot_id: The slot ID for this run. If None, uses get_slot_id() from config.
    """
    effective_slot_id = slot_id if slot_id is not None else get_slot_id()
    ctx = MappingOptimizationContext(slot_id=effective_slot_id)
    _mapping_context.set(ctx)


def _cleanup_on_exit() -> None:
    """Cleanup handler called on program exit (including interrupts).

    Ensures mapping modifications are restored even if the program is
    interrupted with Ctrl+C or otherwise terminated.

    Note: With ContextVar, this only cleans up the context in the main thread.
    Each async task should handle its own cleanup via try/finally blocks
    in the orchestrator.
    """
    ctx = _mapping_context.get()
    if ctx is not None and ctx.modified:
        slot_info = f" (slot {ctx.slot_id})" if ctx.slot_id is not None else ""
        logger.info(f"Program exit detected - restoring modified mappings{slot_info}...")
        try:
            ctx.restore_all()
            logger.info("Mapping restoration on exit complete.")
        except Exception as e:
            logger.error(f"Failed to restore mappings on exit: {e}")


# Register cleanup handler for program exit
import atexit
import signal

atexit.register(_cleanup_on_exit)


def _signal_handler(signum, frame):
    """Handle interrupt signals (Ctrl+C) to restore mappings before exit."""
    logger.info(f"Signal {signum} received - cleaning up mappings...")
    _cleanup_on_exit()
    # Re-raise the signal to allow normal termination
    signal.signal(signum, signal.SIG_DFL)
    signal.raise_signal(signum)


# Register signal handlers for graceful cleanup on interrupt
# Only register in main thread (signal handlers don't work in worker threads)
if threading.current_thread() is threading.main_thread():
    signal.signal(signal.SIGINT, _signal_handler)
    signal.signal(signal.SIGTERM, _signal_handler)


# =============================================================================
# SQL Analysis Tools
# =============================================================================


@tool
def analyze_sql_for_self_joins(
    sparql_query: str,
    dataset: str,
) -> str:
    """
    Analyze the SQL generated by OnTop for a SPARQL query to detect self-joins.

    Uses the /ontop/reformulate endpoint to get the SQL translation,
    then analyzes it for self-join patterns.

    Args:
        sparql_query: The SPARQL query to analyze
        dataset: Dataset ID (e.g., "trn-large", "edu")

    Returns:
        JSON with:
        - success: True/False
        - has_self_join: Whether self-joins were detected
        - self_join_tables: List of tables with self-joins
        - self_join_pattern: The detected pattern (e.g., "FROM STOP_TIMES v1, STOP_TIMES v2")
        - generated_sql: The full SQL query (truncated if very long)
        - error: Error message if analysis failed
    """
    endpoint = get_endpoint_for_dataset(dataset)
    if not endpoint:
        return json.dumps({
            "success": False,
            "error": f"Unknown dataset: {dataset}",
        })

    # Build reformulate URL from SPARQL endpoint
    # e.g., http://localhost:8082/sparql -> http://localhost:8082/ontop/reformulate
    reformulate_url = endpoint.replace("/sparql", "/ontop/reformulate")

    try:
        with httpx.Client(timeout=REFORMULATE_TIMEOUT) as client:
            response = client.get(
                reformulate_url,
                params={"query": sparql_query},
            )

            if response.status_code != 200:
                return json.dumps({
                    "success": False,
                    "error": f"Reformulate API returned {response.status_code}: {response.text[:500]}",
                })

            sql_output = response.text

            # Use sqlglot-based AST analysis (with regex fallback)
            from src.tools.sql_analyzer import detect_self_joins

            self_joins = detect_self_joins(sql_output)
            self_join_tables = list(self_joins.keys())

            # Build display pattern from first detected self-join
            pattern_display = ""
            if self_joins:
                table, aliases = next(iter(self_joins.items()))
                pattern_display = f"FROM {table} {aliases[0]}, {table} {aliases[1]}"

            return json.dumps({
                "success": True,
                "has_self_join": len(self_join_tables) > 0,
                "self_join_tables": self_join_tables,
                "self_join_pattern": pattern_display,
                "generated_sql": sql_output[:2000] + ("..." if len(sql_output) > 2000 else ""),
            }, indent=2)

    except httpx.TimeoutException:
        return json.dumps({
            "success": False,
            "error": f"Reformulate API timed out after {REFORMULATE_TIMEOUT}s",
        })
    except Exception as e:
        return json.dumps({
            "success": False,
            "error": f"Analysis failed: {str(e)}",
        })


# =============================================================================
# Database Schema Tools
# =============================================================================


@tool
def get_table_schema(
    table_name: str,
    dataset: str,
) -> str:
    """
    Get the full schema for a database table: columns, primary keys, and foreign keys.

    Use this to understand the structure of a table before optimizing mappings.
    Foreign key information is essential for understanding cross-table relationships.
    When an object template references an entity from another table, FKs reveal
    which JOINs are needed to obtain the correct context columns.

    Args:
        table_name: Table name (case-insensitive)
        dataset: Dataset ID (used to determine database connection)

    Returns:
        JSON with:
        - success: True/False
        - table: The table name
        - columns: List of {name, type, is_primary_key}
        - primary_key_columns: List of PK column names
        - foreign_keys: List of {column, references_table, references_column}
        - error: Error message if lookup failed
    """
    settings = get_settings()

    db_name = _get_database_name(dataset)
    if not db_name:
        return json.dumps({
            "success": False,
            "error": f"No database mapping for dataset: {dataset}",
        })

    try:
        import mysql.connector

        conn = mysql.connector.connect(
            host=settings.mysql_host,
            port=settings.mysql_port,
            user=settings.mysql_user,
            password=settings.mysql_password,
            database="information_schema",
        )
        cursor = conn.cursor()

        # 1. Get all columns
        cursor.execute("""
            SELECT COLUMN_NAME, COLUMN_TYPE
            FROM COLUMNS
            WHERE TABLE_SCHEMA = %s
            AND UPPER(TABLE_NAME) = UPPER(%s)
            ORDER BY ORAgentic SPARQLL_POSITION
        """, (db_name, table_name))
        columns_raw = cursor.fetchall()

        if not columns_raw:
            # Check if table/database exists
            cursor.execute("""
                SELECT SCHEMA_NAME FROM SCHEMATA WHERE SCHEMA_NAME = %s
            """, (db_name,))
            if not cursor.fetchone():
                cursor.close()
                conn.close()
                return json.dumps({
                    "success": False,
                    "error": f"Database '{db_name}' does not exist",
                })
            cursor.close()
            conn.close()
            return json.dumps({
                "success": False,
                "error": f"Table '{table_name}' not found in database '{db_name}'",
            })

        # 2. Get primary key columns
        cursor.execute("""
            SELECT COLUMN_NAME
            FROM KEY_COLUMN_USAGE
            WHERE TABLE_SCHEMA = %s
            AND UPPER(TABLE_NAME) = UPPER(%s)
            AND CONSTRAINT_NAME = 'PRIMARY'
            ORDER BY ORAgentic SPARQLL_POSITION
        """, (db_name, table_name))
        pk_columns = [row[0].lower() for row in cursor.fetchall()]

        # 3. Get foreign keys
        cursor.execute("""
            SELECT
                kcu.COLUMN_NAME,
                kcu.REFERENCED_TABLE_NAME,
                kcu.REFERENCED_COLUMN_NAME
            FROM KEY_COLUMN_USAGE kcu
            JOIN TABLE_CONSTRAINTS tc
                ON kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
                AND kcu.TABLE_SCHEMA = tc.TABLE_SCHEMA
                AND kcu.TABLE_NAME = tc.TABLE_NAME
            WHERE kcu.TABLE_SCHEMA = %s
            AND UPPER(kcu.TABLE_NAME) = UPPER(%s)
            AND tc.CONSTRAINT_TYPE = 'FOREIGN KEY'
            AND kcu.REFERENCED_TABLE_NAME IS NOT NULL
            ORDER BY kcu.ORAgentic SPARQLL_POSITION
        """, (db_name, table_name))
        fk_rows = cursor.fetchall()

        cursor.close()
        conn.close()

        # Build columns list with PK flag
        columns = [
            {
                "name": col[0].lower(),
                "type": col[1],
                "is_primary_key": col[0].lower() in pk_columns,
            }
            for col in columns_raw
        ]

        # Build FK list
        foreign_keys = [
            {
                "column": row[0].lower(),
                "references_table": row[1],
                "references_column": row[2].lower(),
            }
            for row in fk_rows
        ]

        return json.dumps({
            "success": True,
            "table": table_name,
            "columns": columns,
            "primary_key_columns": pk_columns,
            "foreign_keys": foreign_keys,
            "database": db_name,
        })

    except ImportError:
        return json.dumps({
            "success": False,
            "error": "mysql-connector-python not installed. Run: pip install mysql-connector-python",
        })
    except Exception as e:
        return json.dumps({
            "success": False,
            "error": f"Database query failed: {str(e)}",
        })


@tool
def get_primary_key(
    table_name: str,
    dataset: str,
) -> str:
    """
    Get the primary key columns for a database table.

    Prefer using get_table_schema instead, which also returns foreign keys
    and column types in addition to primary keys.

    Args:
        table_name: Table name (case-insensitive)
        dataset: Dataset ID (used to determine database connection)

    Returns:
        JSON with:
        - success: True/False
        - table: The table name
        - primary_key_columns: List of PK column names
        - error: Error message if lookup failed
    """
    # Delegate to get_table_schema and extract just PKs
    result = json.loads(get_table_schema.invoke({"table_name": table_name, "dataset": dataset}))

    if not result.get("success"):
        return json.dumps(result)

    return json.dumps({
        "success": True,
        "table": result["table"],
        "primary_key_columns": result["primary_key_columns"],
        "database": result["database"],
    })


def _get_database_name(dataset: str) -> str:
    """Map dataset ID to MySQL database name.

    Reads the database name from the dataset's ontop.properties JDBC URL,
    which is the single source of truth for the database connection.

    Falls back to convention-based naming if the properties file is not found.
    """
    # Try to read from ontop.properties (single source of truth)
    import re
    props_path = MAPPINGS_DIR_ROOT / dataset.lower() / "ontop.properties"
    if props_path.exists():
        try:
            text = props_path.read_text(encoding="utf-8")
            match = re.search(r"jdbc\.url=jdbc:mysql://[^/]+/(\w+)", text)
            if match:
                return match.group(1)
        except Exception:
            pass

    # Fallback: convention-based naming
    return dataset.lower().replace("-", "_")


# =============================================================================
# Mapping Analysis Tools
# =============================================================================


@tool
def grep_mapping(
    pattern: str,
    dataset: str,
) -> str:
    """
    Search the R2RML mapping file for a pattern. Returns line numbers and matched lines.

    Use this to find where something is in the mapping file. Then use read_mapping()
    with line_start/line_end to read the context you need.

    Args:
        pattern: Search pattern (case-insensitive substring match)
        dataset: Dataset ID (e.g., "trn", "edu")

    Returns:
        JSON with:
        - success: True/False
        - matches: List of {line_number, matched_line} for each match
        - total_lines: Total lines in the file (so you know the range for read_mapping)
        - mapping_file: Path to the mapping file
    """
    mapping_path = _get_mapping_path(dataset)
    if not mapping_path or not mapping_path.exists():
        return json.dumps({
            "success": False,
            "error": f"Mapping file not found for dataset: {dataset}",
        })

    try:
        lines = mapping_path.read_text(encoding="utf-8").splitlines()
        pattern_lower = pattern.lower()

        matches = []
        for i, line in enumerate(lines):
            if pattern_lower in line.lower():
                matches.append({
                    "line_number": i + 1,
                    "matched_line": line.strip(),
                })

        return json.dumps({
            "success": True,
            "matches": matches,
            "total_lines": len(lines),
            "mapping_file": str(mapping_path),
        }, indent=2)

    except Exception as e:
        return json.dumps({
            "success": False,
            "error": f"Search failed: {str(e)}",
        })


@tool
def read_mapping(
    dataset: str,
    line_start: int | None = None,
    line_end: int | None = None,
) -> str:
    """
    Read the R2RML mapping file for a dataset.

    Use this to read the full mapping or specific line ranges after using grep_mapping.

    Args:
        dataset: Dataset ID (e.g., "trn-large", "edu")
        line_start: Optional start line (1-indexed). If not provided, reads from beginning.
        line_end: Optional end line (1-indexed). If not provided, reads to end.

    Returns:
        JSON with:
        - success: True/False
        - content: The mapping file content (or specified lines)
        - mapping_file: Path to the mapping file
        - total_lines: Total number of lines in the file
    """
    mapping_path = _get_mapping_path(dataset)
    if not mapping_path or not mapping_path.exists():
        return json.dumps({
            "success": False,
            "error": f"Mapping file not found for dataset: {dataset}",
        })

    try:
        lines = mapping_path.read_text(encoding="utf-8").splitlines()
        total_lines = len(lines)

        # Apply line range if specified
        if line_start is not None or line_end is not None:
            start_idx = (line_start - 1) if line_start else 0
            end_idx = line_end if line_end else total_lines
            lines = lines[start_idx:end_idx]
            # Add line numbers for context
            content = "\n".join(f"{start_idx + i + 1}: {line}" for i, line in enumerate(lines))
        else:
            content = "\n".join(lines)

        return json.dumps({
            "success": True,
            "content": content,
            "mapping_file": str(mapping_path),
            "total_lines": total_lines,
        })

    except Exception as e:
        return json.dumps({
            "success": False,
            "error": f"Failed to read mapping: {str(e)}",
        })




# =============================================================================
# Mapping Read Tools (for re-reading relevant context)
# =============================================================================


@tool
def read_relevant_mapping(dataset: str) -> str:
    """
    Re-read the relevant TriplesMap blocks that were provided at the start.

    Use this tool to see the CURRENT state of the mapping sections you are
    working on. This is especially useful after one or more edit_mapping calls
    to verify your changes look correct before continuing.

    The tool returns only the TriplesMap blocks relevant to your task (the same
    ones shown in the initial context), but reflecting any edits you have made.

    Args:
        dataset: Dataset ID (e.g., "trn-large", "edu")

    Returns:
        Formatted text of the relevant TriplesMap blocks in their current state,
        or an error message if the context is not available.
    """
    from src.tools.mapping_context_extractor import extract_relevant_triplesmaps

    ctx = get_mapping_context()

    if not ctx.initial_mapping_path or not ctx.initial_reformulated_sql:
        return json.dumps({
            "success": False,
            "error": "No initial mapping context available. This tool can only be used during a mapping optimization session.",
        })

    mapping_path = Path(ctx.initial_mapping_path)
    if not mapping_path.exists():
        return json.dumps({
            "success": False,
            "error": f"Mapping file not found: {mapping_path}",
        })

    result = extract_relevant_triplesmaps(
        mapping_path=mapping_path,
        reformulated_sql=ctx.initial_reformulated_sql,
    )

    if not result.get("success"):
        return json.dumps({
            "success": False,
            "error": result.get("error", "Failed to extract mapping context"),
        })

    context_text = result.get("context_text", "")
    block_names = result.get("block_names", [])

    if not context_text:
        return json.dumps({
            "success": True,
            "message": "No relevant TriplesMap blocks found.",
            "blocks": [],
        })

    return json.dumps({
        "success": True,
        "blocks_count": len(block_names),
        "block_names": block_names,
    }) + "\n\n" + context_text


# =============================================================================
# Mapping Modification Tools
# =============================================================================


@tool
def edit_mapping(
    dataset: str,
    old_string: str,
    new_string: str,
    replace_all: bool = False,
) -> str:
    """
    Replace a string in the mapping file.

    Use this for ANY modification to the mapping file:
    - IRI templates (rr:template)
    - SQL queries (rr:sqlQuery)
    - Table names, column names, etc.

    Args:
        dataset: Dataset ID (e.g., "trn-large", "edu")
        old_string: The exact string to replace
        new_string: The replacement string
        replace_all: If True, replace ALL occurrences. If False (default), old_string must be unique.

    Returns:
        JSON with:
        - success: True/False
        - replacements: Number of replacements made
        - requires_restart: Whether OnTop needs restart
        - error: Error message if failed
    """
    mapping_path = _get_mapping_path(dataset)
    if not mapping_path or not mapping_path.exists():
        return json.dumps({
            "success": False,
            "error": f"Mapping file not found for dataset: {dataset}",
        })

    # Backup before modification
    context = get_mapping_context()
    context.backup_mapping(str(mapping_path), dataset)

    try:
        content = mapping_path.read_text(encoding="utf-8")

        # Check if old_string exists
        if old_string not in content:
            old_short = old_string.replace("\n", "\\n")[:150]
            logger.warning(f"edit_mapping [{dataset}] FAILED: old_string not found: '{old_short}'")
            return json.dumps({
                "success": False,
                "error": "old_string not found in mapping file",
            })

        count = content.count(old_string)

        # If not replace_all, check uniqueness
        if not replace_all and count > 1:
            old_short = old_string.replace("\n", "\\n")[:150]
            logger.warning(f"edit_mapping [{dataset}] FAILED: not unique ({count}x): '{old_short}'")
            return json.dumps({
                "success": False,
                "error": f"old_string appears {count} times. Use replace_all=True to replace all, or include more context to make it unique.",
            })

        # Perform the replacement
        if replace_all:
            new_content = content.replace(old_string, new_string)
        else:
            new_content = content.replace(old_string, new_string, 1)

        # Write the modified mapping
        mapping_path.write_text(new_content, encoding="utf-8")
        context.mark_modified()

        old_short = old_string.replace("\n", "\\n")[:150]
        new_short = new_string.replace("\n", "\\n")[:150]
        logger.info(f"edit_mapping [{dataset}] replace_all={replace_all} count={count}: '{old_short}' -> '{new_short}'")

        return json.dumps({
            "success": True,
            "replacements": count,
            "requires_restart": True,
        })

    except Exception as e:
        return json.dumps({
            "success": False,
            "error": f"Mapping modification failed: {str(e)}",
        })


@tool
def verify_mapping_syntax(
    dataset: str,
) -> str:
    """
    Verify that the mapping file has valid RDF/Turtle syntax.

    Use this after modifying a mapping to ensure it's still valid.

    Args:
        dataset: Dataset ID

    Returns:
        JSON with:
        - success: True/False
        - valid: Whether the mapping is syntactically valid
        - error: Parsing error message if invalid
    """
    mapping_path = _get_mapping_path(dataset)
    if not mapping_path or not mapping_path.exists():
        return json.dumps({
            "success": False,
            "error": f"Mapping file not found for dataset: {dataset}",
        })

    try:
        from rdflib import Graph

        g = Graph()
        g.parse(str(mapping_path), format="turtle")

        return json.dumps({
            "success": True,
            "valid": True,
            "triple_count": len(g),
        })

    except Exception as e:
        return json.dumps({
            "success": True,  # Tool worked, but mapping is invalid
            "valid": False,
            "error": str(e),
        })


@tool
def validate_template_variables(dataset: str) -> str:
    """
    Validate that all template variables exist in the corresponding SQL queries.

    This checks for the common error:
    "The placeholder(s) X in the target do(es) not occur in source query"

    For each TriplesMap, extracts all {variable} placeholders from templates
    and verifies they exist as column aliases in the SQL SELECT clause.

    Args:
        dataset: Dataset ID

    Returns:
        JSON with:
        - success: True/False
        - valid: True if all variables are present in SQL
        - errors: List of missing variable errors
        - warnings: List of potential issues
    """
    import re

    mapping_path = _get_mapping_path(dataset)
    if not mapping_path or not mapping_path.exists():
        return json.dumps({
            "success": False,
            "error": f"Mapping file not found for dataset: {dataset}",
        })

    try:
        content = mapping_path.read_text(encoding="utf-8")
        errors = []
        warnings = []

        # Find all TriplesMap blocks
        # Pattern: <#Name> or <URI> followed by content until the closing .
        triplesmap_pattern = r'(<#?\w+>|<[^>]+>)\s*(?:a\s+rr:TriplesMap\s*[;.])?(.+?)(?=<#|\Z)'
        blocks = re.findall(triplesmap_pattern, content, re.DOTALL)

        for block_name, block_content in blocks:
            # Skip if this doesn't look like a TriplesMap
            if 'rr:logicalTable' not in block_content and 'rr:tableName' not in block_content:
                continue

            # Extract SQL query or table name
            sql_match = re.search(r'rr:sqlQuery\s*"""(.+?)"""', block_content, re.DOTALL)
            table_match = re.search(r'rr:tableName\s*"([^"]+)"', block_content)

            if sql_match:
                sql = sql_match.group(1)
                # Extract column aliases from SELECT clause
                # Pattern: column AS alias or just column
                select_match = re.search(r'SELECT\s+(.+?)\s+FROM', sql, re.IGNORECASE | re.DOTALL)
                if select_match:
                    select_clause = select_match.group(1)
                    # Find all aliases: "X AS alias" or just column names
                    aliases = set()
                    # Match "something AS alias"
                    for match in re.finditer(r'\bAS\s+(\w+)', select_clause, re.IGNORECASE):
                        aliases.add(match.group(1).lower())
                    # Also match simple column names without AS
                    for match in re.finditer(r'(?:^|,)\s*(\w+)\s*(?:,|$)', select_clause):
                        aliases.add(match.group(1).lower())
                else:
                    aliases = set()
            elif table_match:
                # If using rr:tableName, all columns of that table are available
                # We can't easily validate this without DB access, so skip
                continue
            else:
                continue

            # Extract ALL template variables from this block (subject AND object templates)
            template_vars = set()
            for template_match in re.finditer(r'rr:template\s*"([^"]+)"', block_content):
                template = template_match.group(1)
                # Find all {variable} placeholders
                for var_match in re.finditer(r'\{(\w+)\}', template):
                    template_vars.add(var_match.group(1).lower())

            # Check if all template variables exist in SQL aliases
            for var in template_vars:
                if var not in aliases:
                    errors.append({
                        "triplesmap": block_name,
                        "variable": var,
                        "available_aliases": sorted(aliases),
                        "message": f"Variable '{{{var}}}' in template not found in SQL. Available: {sorted(aliases)}"
                    })

        return json.dumps({
            "success": True,
            "valid": len(errors) == 0,
            "error_count": len(errors),
            "errors": errors[:10],  # Limit to first 10 errors
            "warnings": warnings,
        })

    except Exception as e:
        return json.dumps({
            "success": False,
            "error": f"Validation failed: {str(e)}",
        })


# =============================================================================
# Container Management Tools
# =============================================================================


@tool
def restart_ontop_container(
    dataset: str,
    wait_for_health: bool = True,
) -> str:
    """
    Restart the OnTop container for a dataset to apply mapping changes.

    After modifying a mapping, OnTop must be restarted for changes to take effect.
    This is a synchronous implementation to avoid nested event-loop issues.

    When USE_SLOT_CONTAINERS is enabled and a slot_id is set in context,
    restarts the slot-specific container instead of the shared one.

    Args:
        dataset: Dataset ID
        wait_for_health: Whether to wait for the container to be healthy (default: True)

    Returns:
        JSON with:
        - success: True/False
        - container_name: The container that was restarted
        - healthy: Whether the container is responding (if wait_for_health=True)
        - error: Error message if restart failed
        - slot_id: The slot ID if using slot containers
    """
    import time

    try:
        import docker

        client = docker.from_env()

        # Check for slot-based container naming
        slot_id = get_slot_id()

        # Build the full dataset name with size suffix if needed
        # Datasets with size variants: edu, trn, nrg
        # Datasets without size variants: bsbm, lca
        SIZED_DATASETS = {"edu", "trn", "nrg"}
        base_dataset = dataset.lower().replace('-small', '').replace('-large', '').replace('_small', '').replace('_large', '')

        # Check if dataset already has size suffix
        has_size = any(s in dataset.lower() for s in ['-small', '-large', '_small', '_large'])

        if base_dataset in SIZED_DATASETS and not has_size:
            # Add size suffix from context
            size = get_dataset_size()  # "small" or "large"
            full_dataset = f"{base_dataset}-{size}"
        else:
            full_dataset = dataset

        base_name = full_dataset.replace('-', '_')

        if USE_SLOT_CONTAINERS and slot_id is not None:
            # Slot-specific container: ontop_{dataset}_slot{N}
            container_name = f"ontop_{base_name}_slot{slot_id}"
        else:
            # Shared container: ontop_{dataset}
            container_name = f"ontop_{base_name}"

        try:
            container = client.containers.get(container_name)
        except docker.errors.NotFound:
            return json.dumps({
                "success": False,
                "error": f"Container not found: {container_name}",
                "slot_id": slot_id,
            })

        slot_info = f" (slot {slot_id})" if slot_id is not None else ""
        logger.info(f"Restarting container{slot_info}: {container_name}")
        container.restart(timeout=30)

        if wait_for_health:
            # Wait for container to be healthy by testing actual SPARQL endpoint
            # Note: get_endpoint_for_dataset respects slot_id context automatically
            endpoint = get_endpoint_for_dataset(dataset)

            if endpoint:
                healthy = False
                # Just check if the HTTP endpoint is reachable (no SPARQL query).
                # ASK { ?s ?p ?o } is very expensive on OnTop because it UNIONs all TriplesMaps.
                for attempt in range(30):  # 30 attempts, ~60 seconds total
                    time.sleep(2)
                    try:
                        with httpx.Client(timeout=10) as http_client:
                            response = http_client.get(endpoint)
                            if response.status_code in (200, 400, 404, 406):
                                # 200 = OK, 400/404/406 = endpoint alive but no query provided
                                healthy = True
                                logger.info(f"Container {container_name} SPARQL endpoint ready after {attempt+1} attempts")
                                break
                    except Exception as e:
                        if attempt % 10 == 0:
                            logger.info(f"Health check attempt {attempt+1}: waiting for {container_name}... ({e})")
                        else:
                            logger.debug(f"Health check attempt {attempt+1} failed: {e}")

                if not healthy:
                    logger.warning(f"Container {container_name} did not become healthy after 30 attempts")
                    # Check for container errors (mapping errors, etc.)
                    health_check = check_ontop_container_health(dataset)
                    error_msg = health_check.get("error_message")
                    error_type = health_check.get("error_type")

                    if error_msg:
                        logger.error(f"Container {container_name} error: {error_type} - {error_msg[:200]}")
                        return json.dumps({
                            "success": True,  # Restart was attempted
                            "container_name": container_name,
                            "healthy": False,
                            "error_type": error_type,
                            "error_message": error_msg,
                            "container_status": health_check.get("status"),
                            "slot_id": slot_id,
                        })

                return json.dumps({
                    "success": True,
                    "container_name": container_name,
                    "healthy": healthy,
                    "slot_id": slot_id,
                })

        return json.dumps({
            "success": True,
            "container_name": container_name,
            "slot_id": slot_id,
        })

    except ImportError:
        return json.dumps({
            "success": False,
            "error": "docker package not installed. Run: pip install docker",
        })
    except Exception as e:
        return json.dumps({
            "success": False,
            "error": f"Container operation failed: {str(e)}",
        })


# =============================================================================
# Container Health Check with Error Extraction
# =============================================================================


def check_ontop_container_health(dataset: str) -> dict:
    """
    Check OnTop container health and extract error messages from logs if unhealthy.

    This function checks if the container is running properly or stuck in a restart loop,
    and extracts relevant error messages from the logs (especially mapping errors).

    When USE_SLOT_CONTAINERS is enabled and a slot_id is set in context,
    checks the slot-specific container instead of the shared one.

    Args:
        dataset: Dataset ID (e.g., "trn-large", "edu")

    Returns:
        Dict with:
        - healthy: True/False
        - status: Container status (running, restarting, exited, etc.)
        - error_message: Extracted error if unhealthy (especially mapping errors)
        - error_type: Type of error (mapping_error, startup_error, unknown)
        - slot_id: The slot ID if using slot containers
    """
    import re
    import time

    try:
        import docker
        client = docker.from_env()

        # Check for slot-based container naming
        slot_id = get_slot_id()

        # Build the full dataset name with size suffix if needed
        SIZED_DATASETS = {"edu", "trn", "nrg"}
        base_dataset = dataset.lower().replace('-small', '').replace('-large', '').replace('_small', '').replace('_large', '')
        has_size = any(s in dataset.lower() for s in ['-small', '-large', '_small', '_large'])

        if base_dataset in SIZED_DATASETS and not has_size:
            size = get_dataset_size()
            full_dataset = f"{base_dataset}-{size}"
        else:
            full_dataset = dataset

        base_name = full_dataset.replace('-', '_')

        if USE_SLOT_CONTAINERS and slot_id is not None:
            container_name = f"ontop_{base_name}_slot{slot_id}"
        else:
            container_name = f"ontop_{base_name}"

        try:
            container = client.containers.get(container_name)
        except docker.errors.NotFound:
            return {
                "healthy": False,
                "status": "not_found",
                "error_message": f"Container not found: {container_name}",
                "error_type": "container_not_found",
            }

        # Check container status
        container.reload()
        status = container.status

        # Check if container is in restart loop
        if "restarting" in status.lower():
            # Get logs to find the error
            logs = container.logs(tail=100).decode("utf-8", errors="ignore")

            # Extract mapping error
            error_msg, error_type = _extract_ontop_error(logs)

            return {
                "healthy": False,
                "status": "restarting",
                "error_message": error_msg,
                "error_type": error_type,
            }

        # Container is running - verify SPARQL endpoint works
        if status == "running":
            endpoint = get_endpoint_for_dataset(dataset)
            if endpoint:
                try:
                    with httpx.Client(timeout=5) as http_client:
                        response = http_client.get(
                            endpoint,
                            params={"query": "ASK { ?s ?p ?o } LIMIT 1"},
                            headers={"Accept": "application/sparql-results+json"},
                        )
                        if response.status_code == 200:
                            return {
                                "healthy": True,
                                "status": "running",
                                "error_message": None,
                                "error_type": None,
                            }
                except Exception:
                    pass

            # SPARQL endpoint not responding - check logs
            logs = container.logs(tail=100).decode("utf-8", errors="ignore")
            error_msg, error_type = _extract_ontop_error(logs)

            return {
                "healthy": False,
                "status": "running_but_unhealthy",
                "error_message": error_msg or "SPARQL endpoint not responding",
                "error_type": error_type or "endpoint_error",
            }

        return {
            "healthy": False,
            "status": status,
            "error_message": f"Container in unexpected state: {status}",
            "error_type": "unknown",
        }

    except ImportError:
        return {
            "healthy": False,
            "status": "unknown",
            "error_message": "docker package not installed",
            "error_type": "dependency_error",
        }
    except Exception as e:
        return {
            "healthy": False,
            "status": "unknown",
            "error_message": str(e),
            "error_type": "unknown",
        }


def _extract_ontop_error(logs: str) -> tuple[str | None, str | None]:
    """
    Extract OnTop error messages from container logs.

    Returns:
        Tuple of (error_message, error_type)
    """
    import re

    # Pattern for InvalidMappingSourceQueriesException
    mapping_error_pattern = r"InvalidMappingSourceQueriesException:\s*(.+?)(?:\n|$)"
    match = re.search(mapping_error_pattern, logs, re.DOTALL)
    if match:
        # Get the full error including the mapping details
        error_start = match.start()
        # Find the mapping assertion details
        mapping_assertion_pattern = r"\[id:\s*mapping-\d+.*?source query:.*?\]"
        assertion_match = re.search(mapping_assertion_pattern, logs[error_start:], re.DOTALL)
        if assertion_match:
            full_error = match.group(1).strip()
            # Add the mapping assertion for context
            full_error += "\n" + assertion_match.group(0)
            return full_error, "mapping_error"
        return match.group(1).strip(), "mapping_error"

    # Pattern for other repository errors
    repo_error_pattern = r"RepositoryException:\s*(.+?)(?:\n|$)"
    match = re.search(repo_error_pattern, logs)
    if match:
        return match.group(1).strip(), "repository_error"

    # Pattern for SQL errors
    sql_error_pattern = r"SQLException:\s*(.+?)(?:\n|$)"
    match = re.search(sql_error_pattern, logs)
    if match:
        return match.group(1).strip(), "sql_error"

    # Generic exception
    exception_pattern = r"Exception.*?:\s*(.+?)(?:\n|$)"
    match = re.search(exception_pattern, logs)
    if match:
        return match.group(1).strip(), "startup_error"

    return None, None


# =============================================================================
# Automatic IRI Template Optimization
# =============================================================================


@tool
def analyze_mapping_entities(dataset: str) -> str:
    """
    Analyze all entity types in an R2RML mapping and their IRI patterns.

    This is the first step before optimization - it shows:
    - What entities exist in the mapping
    - How their IRIs are constructed (which variables)
    - How many TriplesMaps use each entity (as subject or object)

    This works for ANY dataset - no dataset-specific knowledge required.

    Args:
        dataset: Dataset ID (e.g., "edu", "trn-large", "nrg")

    Returns:
        JSON with list of entities, their variables, and usage counts.
    """
    mapping_path = _get_mapping_path(dataset)
    if not mapping_path or not mapping_path.exists():
        return json.dumps({
            "success": False,
            "error": f"Mapping file not found for dataset: {dataset}",
        })

    try:
        parser = R2RMLParser(mapping_path)
        entities = parser.get_entity_info()

        return json.dumps({
            "success": True,
            "dataset": dataset,
            "mapping_file": str(mapping_path),
            "total_triples_maps": len(parser.triples_maps),
            "entity_types": len(entities),
            "entities": entities,
        }, indent=2)

    except Exception as e:
        return json.dumps({
            "success": False,
            "error": f"Analysis failed: {str(e)}",
        })


@tool
def analyze_iri_dependencies(
    dataset: str,
    variable: str,
) -> str:
    """
    Analyze all templates that use a specific variable.

    Use this to understand which TriplesMaps would need to be updated
    if you want to change templates using this variable.

    Args:
        dataset: Dataset ID
        variable: Variable name used in templates (e.g., "nr", "trip_id")

    Returns:
        JSON with all subject and object maps using this variable.
    """
    mapping_path = _get_mapping_path(dataset)
    if not mapping_path or not mapping_path.exists():
        return json.dumps({
            "success": False,
            "error": f"Mapping file not found for dataset: {dataset}",
        })

    try:
        parser = R2RMLParser(mapping_path)
        usages = parser.find_templates_with_variable(variable)

        return json.dumps({
            "success": True,
            "dataset": dataset,
            "variable": variable,
            "subject_map_count": len(usages['subject_maps']),
            "object_map_count": len(usages['object_maps']),
            "total_usages": usages['total'],
            "subject_maps": usages['subject_maps'],
            "object_maps": usages['object_maps'],
        }, indent=2)

    except Exception as e:
        return json.dumps({
            "success": False,
            "error": f"Analysis failed: {str(e)}",
        })


@tool
def optimize_entity_iri(
    dataset: str,
    old_template: str,
    new_template: str,
) -> str:
    """
    Replace an IRI template with a new one across ALL usages in the mapping.

    This ensures IRI consistency by finding and replacing the template
    everywhere it appears (both as subject and object).

    IMPORTANT: The templates must match EXACTLY. Use analyze_mapping_entities
    first to see the exact templates used.

    Args:
        dataset: Dataset ID (e.g., "edu-large", "trn-large")
        old_template: The exact current IRI template to replace
        new_template: The new IRI template to use

    Returns:
        JSON with update results.
    """
    mapping_path = _get_mapping_path(dataset)
    if not mapping_path or not mapping_path.exists():
        return json.dumps({
            "success": False,
            "error": f"Mapping file not found for dataset: {dataset}",
        })

    # Backup before modification
    context = get_mapping_context()
    context.backup_mapping(str(mapping_path), dataset)

    try:
        content = mapping_path.read_text(encoding="utf-8")

        # Check if old_template exists in the file
        search_pattern = f'rr:template "{old_template}"'
        if search_pattern not in content:
            return json.dumps({
                "success": False,
                "error": f"Template not found in mapping: {old_template}",
            })

        # VALIDATION: Check if new template variables are available in all affected TriplesMaps
        try:
            parser = R2RMLParser(mapping_path)
            validation = parser.validate_template_variables(old_template, new_template)

            if not validation["valid"]:
                # New variables are not available in some source queries
                error_details = []
                for err in validation["errors"]:
                    error_details.append(
                        f"TriplesMap '{err['triples_map']}': missing columns {err['missing_variables']} "
                        f"(available: {err['available_columns'][:10]}...)"
                    )
                return json.dumps({
                    "success": False,
                    "error": "Template validation failed: new variables not available in source queries",
                    "validation_errors": error_details,
                    "added_variables": validation.get("added_variables", []),
                    "hint": (
                        "The new template uses variables that don't exist in all affected SQL queries. "
                        "For mappings with JOINs, you can only use columns that appear in the SELECT clause. "
                        "Consider using the existing columns or skip optimizing this particular template."
                    ),
                })
        except Exception as e:
            # Validation failed - log warning but continue (OnTop will catch errors on restart)
            logger.warning(f"Template validation failed (continuing anyway): {e}")

        # Count occurrences before replacement
        count = content.count(search_pattern)

        # Replace all occurrences
        new_pattern = f'rr:template "{new_template}"'
        modified_content = content.replace(search_pattern, new_pattern)

        # Write modified content
        mapping_path.write_text(modified_content, encoding="utf-8")
        context.mark_modified()

        # Verify syntax
        verify_result = json.loads(verify_mapping_syntax.invoke({"dataset": dataset}))
        if not verify_result.get("valid", False):
            # Rollback on syntax error
            mapping_path.write_text(content, encoding="utf-8")
            return json.dumps({
                "success": False,
                "error": f"Mapping syntax invalid after modification: {verify_result.get('error')}",
                "rolled_back": True,
            })

        # NOTE: OnTop restart is now handled by the SPARQL Agent after all changes are complete
        # This allows batching multiple template changes without waiting for restarts

        return json.dumps({
            "success": True,
            "old_template": old_template,
            "new_template": new_template,
            "replacements": count,
            "requires_restart": True,  # Signal that OnTop needs restart
        }, indent=2)

    except Exception as e:
        return json.dumps({
            "success": False,
            "error": f"Optimization failed: {str(e)}",
        })


# =============================================================================
# Helper Functions
# =============================================================================


def _get_mapping_path(dataset: str) -> Path | None:
    """Get the path to the mapping file for a dataset.

    When USE_SLOT_CONTAINERS is enabled and a slot_id is set in context,
    returns the slot-specific mapping path. Otherwise, returns the shared
    mapping path from MAPPINGS_DIR_ROOT.
    """
    dataset_lower = dataset.lower()

    # Build the full dataset name with size suffix if needed
    # Datasets with size variants: edu, trn, nrg
    SIZED_DATASETS = {"edu", "trn", "nrg"}
    base_dataset = dataset_lower.replace('-small', '').replace('-large', '').replace('_small', '').replace('_large', '')
    has_size = any(s in dataset_lower for s in ['-small', '-large', '_small', '_large'])

    if base_dataset in SIZED_DATASETS and not has_size:
        size = get_dataset_size()
        full_dataset = f"{base_dataset}-{size}"
    else:
        full_dataset = dataset_lower

    # Check for slot-specific mapping path first (if slots are enabled)
    slot_id = get_slot_id()
    if USE_SLOT_CONTAINERS and slot_id is not None:
        slot_mappings_dir = MAPPINGS_DIR_ROOT.parent / "mappings-slots" / f"slot{slot_id}"

        # Convention: mappings-slots/slot{N}/{dataset}/mapping.ttl
        slot_mapping_path = slot_mappings_dir / full_dataset / "mapping.ttl"
        if slot_mapping_path.exists():
            return slot_mapping_path

        # Try with underscores instead of hyphens
        slot_mapping_path = slot_mappings_dir / full_dataset.replace("-", "_") / "mapping.ttl"
        if slot_mapping_path.exists():
            return slot_mapping_path

        # Try other common names
        for name in ["mapping.ttl", "ontop.obda", "mapping.obda"]:
            slot_mapping_path = slot_mappings_dir / full_dataset / name
            if slot_mapping_path.exists():
                return slot_mapping_path

    # Fallback to shared mapping (original behavior)
    # Convention: mappings/{dataset}/mapping.ttl
    mapping_path = MAPPINGS_DIR_ROOT / full_dataset / "mapping.ttl"
    if mapping_path.exists():
        return mapping_path

    # Try with underscores instead of hyphens
    mapping_path = MAPPINGS_DIR_ROOT / full_dataset.replace("-", "_") / "mapping.ttl"
    if mapping_path.exists():
        return mapping_path

    # Try other common names
    for name in ["mapping.ttl", "ontop.obda", "mapping.obda"]:
        mapping_path = MAPPINGS_DIR_ROOT / full_dataset / name
        if mapping_path.exists():
            return mapping_path

    return None


# =============================================================================
# Tool Collections
# =============================================================================


# Tools for the Mapping Optimizer Agent
# Workflow: grep → read → edit (with automatic OnTop restart)
# 1. grep_mapping - find where a table appears in the mapping
# 2. read_mapping - read the relevant section to understand the structure
# 3. get_primary_key - get PK columns from the database
# 4. edit_mapping - replace the IRI template (auto-restarts OnTop)
# 5. verify_mapping_syntax - validate the modified mapping
MAPPING_OPTIMIZER_TOOLS = [
    grep_mapping,              # Search mapping file, returns line numbers
    read_mapping,              # Read mapping file (agent chooses line range)
    get_primary_key,           # Get PK columns from MySQL
    edit_mapping,              # String replacement + auto-restart OnTop
    verify_mapping_syntax,     # Verify RDF/Turtle syntax
]

# High-level tools for automatic IRI optimization (Generic - works for all datasets)
# These tools use rdflib to parse R2RML and handle IRI consistency automatically
MAPPING_OPTIMIZER_TOOLS_V2 = [
    analyze_mapping_entities,  # Discover all entity types and their IRI patterns
    analyze_iri_dependencies,  # Find all usages of a specific variable
    optimize_entity_iri,       # Replace IRI template consistently across mapping
    get_primary_key,           # Get PK columns from MySQL
    verify_mapping_syntax,     # Verify RDF/Turtle syntax
]

# Tools for autonomous mapping optimization workflow
# Agent explores the mapping file itself using grep/read, then edits
MAPPING_OPTIMIZER_TOOLS_V3 = [
    grep_mapping,              # Search full mapping file for patterns (find all references)
    read_mapping,              # Read any section of the mapping file (full context)
    edit_mapping,              # String replacement (use replace_all=True for templates)
    get_table_schema,          # Get full schema: columns, PKs, and FKs from MySQL
    verify_mapping_syntax,     # Verify RDF/Turtle syntax
]


__all__ = [
    # Data classes
    "MappingChange",
    "MappingOptimizerResult",
    "TripleMapInfo",
    "R2RMLParser",
    # Context management
    "MappingOptimizationContext",
    "get_mapping_context",
    "reset_mapping_context",
    # Tools (low-level)
    "grep_mapping",
    "read_mapping",
    "read_relevant_mapping",
    "get_table_schema",
    "get_primary_key",
    "edit_mapping",
    "verify_mapping_syntax",
    "restart_ontop_container",
    # Tools (high-level automatic optimization - generic for all datasets)
    "analyze_mapping_entities",
    "analyze_iri_dependencies",
    "optimize_entity_iri",
    # Tool collections
    "MAPPING_OPTIMIZER_TOOLS",
    "MAPPING_OPTIMIZER_TOOLS_V2",
    "MAPPING_OPTIMIZER_TOOLS_V3",
]
