"""
Mapping Context Extractor for Pre-populating Agent Context.

This module provides functions to deterministically extract relevant TriplesMap
definitions from an R2RML mapping based on the SQL query generated by OnTop.

The goal is to pre-populate the Mapping Optimizer Agent's context with the
exact raw mapping sections it needs, eliminating the need for initial tool calls.

Workflow:
1. SQL from OnTop /reformulate → extract table names
2. Table names → find TriplesMaps that reference these tables
3. Return raw TriplesMap text blocks (not parsed data)

Supports all R2RML Turtle formats:
- EDU style: <#Name> with multi-line SQL
- TRN style: <name> a rr:TriplesMap; with rr:tableName
- NRG style: <Mapping:00001:...> a rr:TriplesMap; with single-line SQL
"""

import re
import logging
from pathlib import Path
from dataclasses import dataclass

from rdflib import Graph, Namespace, URIRef
from rdflib.namespace import RDF

logger = logging.getLogger(__name__)

# R2RML namespace
RR = Namespace("http://www.w3.org/ns/r2rml#")


@dataclass
class TriplesMapBlock:
    """A raw TriplesMap block extracted from the mapping file."""
    name: str  # e.g., "BachelorCandidate" or full URI
    uri: str  # Full URI of the TriplesMap
    start_line: int
    end_line: int
    raw_text: str
    tables_referenced: list[str]  # Tables this TriplesMap uses
    subject_template: str | None = None  # The rr:template value for the subject


def _extract_subject_template(raw_text: str) -> str | None:
    """
    Extract the subject template from a TriplesMap block.

    Looks for patterns like:
    - rr:subjectMap [ rr:template "http://..." ];
    - rr:template "http://...";
    """
    # Pattern for rr:template inside subjectMap
    pattern = r'rr:template\s+"([^"]+)"'
    match = re.search(pattern, raw_text)
    if match:
        return match.group(1)
    return None


def extract_tables_from_sql(sql: str) -> list[str]:
    """
    Extract table names from OnTop's reformulated SQL.

    Uses sqlglot AST parsing with regex fallback for robustness.

    Args:
        sql: The SQL query from OnTop's /reformulate endpoint

    Returns:
        List of unique table names (lowercase)
    """
    from src.tools.sql_analyzer import extract_tables

    return extract_tables(sql)


def parse_triples_map_blocks(mapping_content: str, mapping_path: Path | str | None = None) -> list[TriplesMapBlock]:
    """
    Parse a Turtle mapping file into individual TriplesMap blocks.

    Uses rdflib to reliably identify TriplesMaps, then extracts their raw text
    from the file. This approach works for all R2RML Turtle formats.

    Args:
        mapping_content: Full content of the mapping.ttl file
        mapping_path: Optional path for rdflib parsing (uses content if not provided)

    Returns:
        List of TriplesMapBlock objects
    """
    # Step 1: Use rdflib to find all TriplesMaps and their tables
    graph = Graph()
    try:
        graph.parse(data=mapping_content, format="turtle")
    except Exception as e:
        logger.warning(f"Failed to parse mapping with rdflib: {e}")
        return []

    # Find all TriplesMaps (subjects with rr:logicalTable)
    triples_maps = {}
    for tm_uri in graph.subjects(RR.logicalTable, None):
        uri_str = str(tm_uri)

        # Extract short name from URI
        if '#' in uri_str:
            name = uri_str.split('#')[-1]
        elif '/' in uri_str:
            name = uri_str.split('/')[-1]
        else:
            name = uri_str

        # Get table references from logicalTable
        tables = set()
        for lt in graph.objects(tm_uri, RR.logicalTable):
            # Check for tableName
            for tn in graph.objects(lt, RR.tableName):
                tables.add(str(tn).lower())
            # Check for sqlQuery
            for sq in graph.objects(lt, RR.sqlQuery):
                sql = str(sq)
                # Extract table names from SQL
                for match in re.finditer(r'FROM\s+(\w+)', sql, re.IGNORECASE):
                    tables.add(match.group(1).lower())
                for match in re.finditer(r'JOIN\s+(\w+)', sql, re.IGNORECASE):
                    tables.add(match.group(1).lower())

        triples_maps[uri_str] = {
            'name': name,
            'tables': sorted(tables),
        }

    # Step 2: Find raw text blocks in the file for each TriplesMap
    lines = mapping_content.split('\n')
    blocks = []

    for uri_str, info in triples_maps.items():
        # Create a pattern to find this TriplesMap in the source
        # Handle both <#Name> and <full-uri> formats
        if uri_str.startswith('file://'):
            # Local URI like file:///path#Name - search for <#Name>
            if '#' in uri_str:
                search_pattern = '<#' + uri_str.split('#')[-1] + '>'
            else:
                search_pattern = '<' + uri_str.split('/')[-1] + '>'
        else:
            # Full URI - search for the URI itself or just the local name
            search_patterns = [
                '<' + uri_str + '>',  # Full URI
                '<#' + info['name'] + '>',  # Hash URI
                '<' + info['name'] + '>',  # Local name only
            ]
            search_pattern = None
            for pattern in search_patterns:
                for i, line in enumerate(lines):
                    if pattern in line:
                        search_pattern = pattern
                        break
                if search_pattern:
                    break

        if not search_pattern:
            logger.debug(f"Could not find source pattern for TriplesMap: {uri_str}")
            continue

        # Find the start line
        start_line = None
        for i, line in enumerate(lines):
            if search_pattern in line:
                start_line = i
                break

        if start_line is None:
            continue

        # Find the end line (next empty line after a period, or next TriplesMap)
        end_line = start_line + 1
        brace_depth = 0
        for i in range(start_line, len(lines)):
            line = lines[i]
            brace_depth += line.count('[') - line.count(']')

            # End of TriplesMap: line ends with . and braces are balanced
            if line.rstrip().endswith('.') and brace_depth == 0:
                end_line = i + 1
                break

        # Extract the raw text
        raw_text = '\n'.join(lines[start_line:end_line])

        # Extract subject template
        subject_template = _extract_subject_template(raw_text)

        blocks.append(TriplesMapBlock(
            name=info['name'],
            uri=uri_str,
            start_line=start_line + 1,  # 1-indexed
            end_line=end_line,
            raw_text=raw_text,
            tables_referenced=info['tables'],
            subject_template=subject_template,
        ))

    return blocks


def _extract_tables_from_triplesmap(block_text: str) -> list[str]:
    """
    Extract table names referenced by a TriplesMap block.

    Handles:
    - rr:tableName "tableName"
    - FROM tableName in rr:sqlQuery
    - JOIN tableName in rr:sqlQuery
    """
    tables = set()

    # Pattern 1: rr:tableName "tableName"
    tablename_match = re.search(r'rr:tableName\s+"(\w+)"', block_text)
    if tablename_match:
        tables.add(tablename_match.group(1).lower())

    # Pattern 2: FROM in SQL query
    sql_match = re.search(r'rr:sqlQuery\s+"""(.+?)"""', block_text, re.DOTALL)
    if sql_match:
        sql = sql_match.group(1)

        # FROM tableName
        for match in re.finditer(r'FROM\s+(\w+)', sql, re.IGNORECASE):
            tables.add(match.group(1).lower())

        # JOIN tableName
        for match in re.finditer(r'JOIN\s+(\w+)', sql, re.IGNORECASE):
            tables.add(match.group(1).lower())

    return sorted(tables)


def extract_relevant_triplesmaps(
    mapping_path: Path | str,
    reformulated_sql: str,
) -> dict:
    """
    Extract TriplesMap blocks relevant to a SQL query.

    This is the main function for pre-populating agent context.

    Args:
        mapping_path: Path to the R2RML mapping file
        reformulated_sql: SQL from OnTop's /reformulate endpoint

    Returns:
        Dict with:
        - tables_in_sql: Tables found in the SQL
        - relevant_blocks: List of TriplesMapBlock objects
        - context_text: Formatted text ready for agent context
    """
    mapping_path = Path(mapping_path)
    if not mapping_path.exists():
        return {
            "success": False,
            "error": f"Mapping file not found: {mapping_path}",
        }

    # Step 1: Extract tables from SQL
    tables_in_sql = extract_tables_from_sql(reformulated_sql)
    logger.info(f"Tables in SQL: {tables_in_sql}")

    # Step 2: Parse mapping into blocks
    content = mapping_path.read_text(encoding="utf-8")
    all_blocks = parse_triples_map_blocks(content)
    logger.info(f"Total TriplesMap blocks: {len(all_blocks)}")

    # Step 3: Find blocks that reference the SQL tables
    relevant_blocks = []
    for block in all_blocks:
        # Check if any of the block's tables are in the SQL
        if any(t in tables_in_sql for t in block.tables_referenced):
            relevant_blocks.append(block)

    logger.info(f"Relevant TriplesMap blocks: {len(relevant_blocks)}")

    # Step 4: Format as context text
    context_text = _format_context_text(relevant_blocks, tables_in_sql)

    return {
        "success": True,
        "tables_in_sql": tables_in_sql,
        "relevant_blocks": relevant_blocks,
        "block_names": [b.name for b in relevant_blocks],
        "context_text": context_text,
    }


def _format_context_text(blocks: list[TriplesMapBlock], tables: list[str]) -> str:
    """
    Format TriplesMap blocks as minimal text for agent context.

    Groups blocks by subject template but shows ALL blocks (not just one representative).
    Each TriplesMap has its own SQL query that may need modification.
    Only outputs the raw data - no explanations (those belong in system prompt).
    """
    if not blocks:
        return ""

    # Group blocks by subject template
    template_groups: dict[str, list[TriplesMapBlock]] = {}
    no_template_blocks: list[TriplesMapBlock] = []

    for block in blocks:
        if block.subject_template:
            if block.subject_template not in template_groups:
                template_groups[block.subject_template] = []
            template_groups[block.subject_template].append(block)
        else:
            no_template_blocks.append(block)

    lines = []

    # Format grouped blocks - show ALL blocks, each has different SQL!
    for template, group_blocks in sorted(template_groups.items(), key=lambda x: -len(x[1])):
        all_names = [b.name for b in group_blocks]

        lines.extend([
            f"TEMPLATE: {template}",
            f"USED_IN: {', '.join(all_names)} ({len(group_blocks)} TriplesMaps)",
            "",
        ])

        # Show ALL blocks - each has its own SQL query that needs modification!
        for block in group_blocks:
            lines.extend([
                block.raw_text.strip(),
                "",
            ])

        lines.extend([
            "---",
            "",
        ])

    # Show blocks without templates
    for block in no_template_blocks:
        lines.extend([
            f"TRIPLESMAP: {block.name}",
            "",
            block.raw_text.strip(),
            "",
            "---",
            "",
        ])

    return '\n'.join(lines)


def get_mapping_context_for_agent(
    mapping_path: Path | str,
    reformulated_sql: str,
    sparql_query: str,
) -> str:
    """
    Extract relevant TriplesMap blocks for the Mapping Optimizer Agent.

    Returns only the raw mapping data - no explanations.

    Args:
        mapping_path: Path to the R2RML mapping file
        reformulated_sql: SQL from OnTop's /reformulate endpoint
        sparql_query: The original SPARQL query (unused, kept for API compat)

    Returns:
        Raw TriplesMap blocks as text
    """
    result = extract_relevant_triplesmaps(mapping_path, reformulated_sql)

    if not result.get("success"):
        return ""

    return result["context_text"]


# Export for use in agent
__all__ = [
    "extract_tables_from_sql",
    "parse_triples_map_blocks",
    "extract_relevant_triplesmaps",
    "get_mapping_context_for_agent",
    "TriplesMapBlock",
]
