"""SQL analysis utilities using sqlglot AST parsing.

Provides robust SQL analysis for the Mapping Optimizer, replacing
regex-based patterns with proper AST traversal. Falls back to regex
if sqlglot cannot parse the SQL (e.g. non-standard Ontop SQL).

Used by:
- mapping_optimizer_tools.py (self-join detection)
- mapping_context_extractor.py (table extraction)
"""

from __future__ import annotations

import dataclasses
import logging
import re

from sqlglot import exp, parse_one
from sqlglot.errors import ErrorLevel

logger = logging.getLogger(__name__)


# =============================================================================
# Data classes
# =============================================================================


@dataclasses.dataclass
class JoinCondition:
    """A single JOIN condition extracted from SQL."""

    left_table: str
    left_column: str
    right_table: str
    right_column: str


@dataclasses.dataclass
class SQLAnalysis:
    """Structured result of a full SQL analysis.

    Provides all information the Mapping Optimizer Agent needs
    about the SQL generated by Ontop's /reformulate endpoint.
    """

    tables: list[str]
    table_aliases: dict[str, list[str]]
    self_joins: dict[str, list[str]]
    has_self_join: bool
    join_conditions: list[JoinCondition]
    union_branch_count: int
    raw_sql: str


# =============================================================================
# Public API
# =============================================================================


def extract_tables(sql: str) -> list[str]:
    """Extract all table names from SQL using AST parsing.

    Falls back to regex if sqlglot cannot parse the SQL.

    Returns:
        Sorted list of unique table names (lowercase).
    """
    try:
        tables = _extract_tables_ast(sql)
        if tables:
            return tables
        # AST parsed but found nothing — try regex
        return _extract_tables_regex(sql)
    except Exception:
        logger.debug("sqlglot parse failed, falling back to regex", exc_info=True)
        return _extract_tables_regex(sql)


def detect_self_joins(sql: str) -> dict[str, list[str]]:
    """Detect self-joins: same table referenced multiple times with different aliases.

    Falls back to regex if sqlglot cannot parse the SQL.

    Returns:
        Dict mapping table_name (lowercase) -> list of aliases.
        Only tables with 2+ references (= self-joins) are included.
        Empty dict if no self-joins detected.
    """
    try:
        result = _detect_self_joins_ast(sql)
        if result is not None:
            return result
        return _detect_self_joins_regex(sql)
    except Exception:
        logger.debug("sqlglot parse failed for self-join detection, falling back to regex", exc_info=True)
        return _detect_self_joins_regex(sql)


def analyze_sql(sql: str) -> SQLAnalysis:
    """Full SQL analysis: tables, self-joins, join conditions, union branches.

    Combines all analysis in one pass. Falls back gracefully for
    each component that cannot be parsed.
    """
    tables = extract_tables(sql)
    self_joins = detect_self_joins(sql)

    # Table aliases (includes non-self-joined tables too)
    table_aliases = _extract_table_aliases(sql)

    # Join conditions
    join_conditions = _extract_join_conditions(sql)

    # Count UNION ALL branches
    union_branch_count = _count_union_branches(sql)

    return SQLAnalysis(
        tables=tables,
        table_aliases=table_aliases,
        self_joins=self_joins,
        has_self_join=len(self_joins) > 0,
        join_conditions=join_conditions,
        union_branch_count=union_branch_count,
        raw_sql=sql[:2000] + ("..." if len(sql) > 2000 else ""),
    )


# =============================================================================
# AST-based implementations (sqlglot)
# =============================================================================


def _extract_tables_ast(sql: str) -> list[str]:
    """Extract tables via sqlglot AST traversal."""
    ast = parse_one(sql, dialect="mysql", error_level=ErrorLevel.RAISE)
    tables = set()
    for table in ast.find_all(exp.Table):
        name = table.name
        if name:
            tables.add(name.lower())
    return sorted(tables)


def _detect_self_joins_ast(sql: str) -> dict[str, list[str]] | None:
    """Detect self-joins via sqlglot AST traversal.

    Returns None if parsing fails (caller should use regex fallback).
    """
    ast = parse_one(sql, dialect="mysql", error_level=ErrorLevel.RAISE)
    table_refs: dict[str, list[str]] = {}
    for table in ast.find_all(exp.Table):
        name = table.name
        if not name:
            continue
        name_lower = name.lower()
        alias = table.alias.lower() if table.alias else name_lower
        table_refs.setdefault(name_lower, []).append(alias)

    return {t: aliases for t, aliases in table_refs.items() if len(aliases) > 1}


def _extract_table_aliases(sql: str) -> dict[str, list[str]]:
    """Extract all table→alias mappings (not just self-joins)."""
    try:
        ast = parse_one(sql, dialect="mysql", error_level=ErrorLevel.RAISE)
        table_refs: dict[str, list[str]] = {}
        for table in ast.find_all(exp.Table):
            name = table.name
            if not name:
                continue
            name_lower = name.lower()
            alias = table.alias.lower() if table.alias else name_lower
            table_refs.setdefault(name_lower, []).append(alias)
        return table_refs
    except Exception:
        return {}


def _extract_join_conditions(sql: str) -> list[JoinCondition]:
    """Extract JOIN ON conditions from the SQL."""
    conditions = []
    try:
        ast = parse_one(sql, dialect="mysql", error_level=ErrorLevel.RAISE)

        # Build alias→table mapping for resolving column references
        alias_to_table: dict[str, str] = {}
        for table in ast.find_all(exp.Table):
            name = table.name
            if not name:
                continue
            alias = table.alias or name
            alias_to_table[alias.lower()] = name.lower()

        # Find all EQ conditions in JOINs
        for join in ast.find_all(exp.Join):
            on_clause = join.args.get("on")
            if not on_clause:
                continue
            for eq in on_clause.find_all(exp.EQ):
                left = eq.left
                right = eq.right
                if isinstance(left, exp.Column) and isinstance(right, exp.Column):
                    left_table = alias_to_table.get(
                        (left.table or "").lower(), (left.table or "").lower()
                    )
                    right_table = alias_to_table.get(
                        (right.table or "").lower(), (right.table or "").lower()
                    )
                    conditions.append(
                        JoinCondition(
                            left_table=left_table,
                            left_column=(left.name or "").lower(),
                            right_table=right_table,
                            right_column=(right.name or "").lower(),
                        )
                    )
    except Exception:
        logger.debug("Could not extract join conditions via AST", exc_info=True)

    return conditions


def _count_union_branches(sql: str) -> int:
    """Count the number of UNION / UNION ALL branches."""
    try:
        ast = parse_one(sql, dialect="mysql", error_level=ErrorLevel.RAISE)
        unions = list(ast.find_all(exp.Union))
        if not unions:
            return 1
        # Each Union node represents one UNION, so N unions = N+1 branches
        return len(unions) + 1
    except Exception:
        # Regex fallback: count "UNION ALL" or "UNION" occurrences
        count = len(re.findall(r'\bUNION\s+(?:ALL\s+)?', sql, re.IGNORECASE))
        return count + 1 if count > 0 else 1


# =============================================================================
# Regex fallbacks (preserved from existing code)
# =============================================================================


def _extract_tables_regex(sql: str) -> list[str]:
    """Fallback table extraction using regex.

    Preserved from mapping_context_extractor.py for cases where
    sqlglot cannot parse Ontop's non-standard SQL output.
    """
    tables = set()

    # Pattern 1: FROM `table` or FROM table (with optional alias)
    from_pattern = r'FROM\s+`?(\w+)`?(?:\s+\w+)?(?:\s*,|\s+WHERE|\s+JOIN|\s+INNER|\s+LEFT|\s+RIGHT|$)'

    # Pattern 2: Comma-separated tables in FROM clause
    from_multi_pattern = r'FROM\s+(.+?)\s+(?:WHERE|INNER|LEFT|RIGHT|JOIN|$)'

    # Pattern 3: JOIN clauses
    join_pattern = r'(?:INNER\s+|LEFT\s+|RIGHT\s+)?JOIN\s+`?(\w+)`?\s+'

    # Extract from simple FROM clauses
    for match in re.finditer(from_pattern, sql, re.IGNORECASE):
        tables.add(match.group(1).lower())

    # Extract from multi-table FROM clauses
    from_match = re.search(from_multi_pattern, sql, re.IGNORECASE | re.DOTALL)
    if from_match:
        from_clause = from_match.group(1)
        for part in from_clause.split(','):
            part = part.strip()
            table_match = re.match(r'`?(\w+)`?(?:\s+\w+)?', part)
            if table_match:
                tables.add(table_match.group(1).lower())

    # Extract from JOIN clauses
    for match in re.finditer(join_pattern, sql, re.IGNORECASE):
        tables.add(match.group(1).lower())

    return sorted(tables)


def _detect_self_joins_regex(sql: str) -> dict[str, list[str]]:
    """Fallback self-join detection using regex.

    Preserved from mapping_optimizer_tools.py for cases where
    sqlglot cannot parse the SQL.
    """
    self_join_tables: dict[str, list[str]] = {}

    # Pattern 1: FROM table v1, table v2
    from_pattern = r'FROM\s+`?(\w+)`?\s+(\w+)\s*,\s*`?\1`?\s+(\w+)'
    for match in re.finditer(from_pattern, sql, re.IGNORECASE):
        table = match.group(1).lower()
        alias1 = match.group(2).lower()
        alias2 = match.group(3).lower()
        self_join_tables.setdefault(table, []).extend([alias1, alias2])

    # Pattern 2: JOIN table alias ON ... table.
    join_pattern = r'JOIN\s+`?(\w+)`?\s+(\w+)\s+ON.*?\1\.'
    for match in re.finditer(join_pattern, sql, re.IGNORECASE):
        table = match.group(1).lower()
        alias = match.group(2).lower()
        if table not in self_join_tables:
            self_join_tables[table] = [table, alias]
        elif alias not in self_join_tables[table]:
            self_join_tables[table].append(alias)

    return self_join_tables
